export {
  ExerciseFeedback,
  ExerciseRenderer,
  MistakeSummary,
  ModuleCard,
  ResultActions,
  ResumeTrainingPrompt,
  GuestSessionImportPrompt,
  ScoreSummary,
  TextAnswerExercise,
  TrainingResult,
  TrainingSession,
} from "./components";
export type {
  ChoiceExerciseProps,
  ExerciseFeedbackProps,
  ExerciseRendererProps,
  FillBlankExerciseProps,
  MatchingExerciseProps,
  MistakeSummaryProps,
  ModuleCardProps,
  ResultActionsProps,
  ResumeTrainingPromptProps,
  GuestSessionImportPromptProps,
  ScoreSummaryProps,
  TextAnswerExerciseProps,
  TrainingResultProps,
  TrainingSessionProps,
} from "./components";
export { ExerciseRepositoryError, LocalExerciseRepository, LocalModuleRepository } from "./data";
export type {
  ExerciseQuery,
  ExerciseRepository,
  ExerciseRepositoryErrorCode,
  ModuleRepository,
} from "./data";
export {
  ANSWER_REASON_CODES,
  CheckerRegistry,
  CheckerRegistryError,
  EXERCISE_DIFFICULTIES,
  EXERCISE_SCHEMA_VERSION,
  ModuleRegistry,
  ModuleRegistryError,
  TRAINING_SESSION_MODES,
  TRAINING_SESSION_SCHEMA_VERSION,
  TRAINING_SESSION_STATUSES,
  TrainingSessionError,
  buildTrainingResultSnapshot,
  createMistakeRetrySessionConfig,
  createTrainingSession,
  evaluateAnswer,
  formatCanonicalAnswerLabel,
  formatSubmittedAnswerLabel,
  normalizeAnswer,
  seededShuffle,
  selectCurrentAttempt,
  selectCurrentExercise,
  selectCurrentExerciseId,
  selectHasAnsweredCurrent,
  selectMistakeExerciseIds,
  selectProgress,
  selectPublishedModules,
  selectPublishedTopics,
  selectResultSummary,
  selectScoreSummary,
  submitTrainingAnswer,
  submitTrainingAnswerForExercise,
  trainingSessionReducer,
} from "./domain";
export type {
  AcceptedAnswer,
  AnswerEvaluation,
  AnswerReasonCode,
  AnswerSubmission,
  BuildTrainingResultSnapshotOptions,
  ChoiceAnswerEvaluation,
  ChoiceAnswerSubmission,
  ChoiceCorrectAnswer,
  ChoiceExercise,
  CorrectAnswerSnapshot,
  Exercise,
  ExerciseDifficulty,
  ExerciseOption,
  ExerciseSchemaVersion,
  ExerciseScoring,
  ExerciseText,
  FillBlankAnswerEvaluation,
  FillBlankAnswerItem,
  FillBlankAnswerSubmission,
  FillBlankCorrectAnswer,
  FillBlankDefinition,
  FillBlankExercise,
  FillBlankItemResult,
  FreeResponseAnswerEvaluation,
  FreeResponseAnswerSubmission,
  FreeResponseCorrectAnswer,
  FreeResponseExercise,
  HonorificChoiceExercise,
  MatchingAnswerEvaluation,
  MatchingAnswerItem,
  MatchingAnswerSubmission,
  MatchingCorrectAnswer,
  MatchingExercise,
  MatchingHonorificExercise,
  MatchingItemResult,
  MatchingPair,
  MatchingTranslationExercise,
  MeaningChoiceExercise,
  ModuleRegistryErrorCode,
  PlainChoiceExercise,
  TrainingAttemptSnapshot,
  TrainingResultMistake,
  TrainingResultSnapshot,
  TrainingResultTopicBreakdown,
  TrainingSessionAction,
  TrainingSessionConfig,
  TrainingSessionContentSnapshot,
  TrainingSessionErrorCode,
  TrainingSessionMode,
  TrainingSessionProgress,
  TrainingSessionResultSummary,
  TrainingSessionSchemaVersion,
  TrainingSessionScoreSummary,
  TrainingSessionState,
  TrainingSessionStatus,
} from "./domain";
export {
  DEMO_TRAINING_MODULE_SLUG,
  DEMO_TRAINING_SEED,
  DEMO_TRAINING_SESSION_ID,
} from "./sessionConstants";
export { useTrainingSession } from "./hooks/useTrainingSession";
export type {
  AnswerDraft,
  ChoiceAnswerDraft,
  FillBlankAnswerDraft,
  FreeResponseAnswerDraft,
  MatchingAnswerDraft,
  UseTrainingSessionOptions,
  UseTrainingSessionResult,
} from "./hooks/useTrainingSession";
export {
  persistTrainingSessionState,
  usePersistedSessionBootstrap,
} from "./hooks/usePersistedTrainingSession";
export type {
  PersistedSessionBootstrap,
  UsePersistedSessionBootstrapOptions,
} from "./hooks/usePersistedTrainingSession";
export {
  LocalTrainingSessionStore,
  TRAINING_SESSION_STORAGE_KEY,
  TRAINING_SESSION_STORAGE_VERSION,
  TRAINING_SESSION_TTL_MS,
} from "./persistence";
export type {
  LocalTrainingSessionStoreOptions,
  PersistedTrainingSessionRecord,
  TrainingSessionClock,
  TrainingSessionLoadResult,
  TrainingSessionStorageAdapter,
  TrainingSessionStorageVersion,
} from "./persistence";
export {
  describeFillBlankTemplate,
  parseFillBlankTemplate,
  toExerciseTextView,
  toExerciseView,
  toPublicExercise,
  toPublicExercises,
} from "./presentation";
export type {
  ChoiceExerciseView,
  ChoiceOptionView,
  ExerciseTextView,
  ExerciseView,
  FillBlankExerciseView,
  FillBlankTemplateSegment,
  FreeResponseExerciseView,
  MatchingExerciseView,
  MatchingLeftItemView,
  MatchingRightOptionView,
  ToExerciseViewOptions,
  PublicExercise,
} from "./presentation";
