export {
  ExerciseFeedback,
  ExerciseRenderer,
  ModuleCard,
  TextAnswerExercise,
  TrainingSession,
} from "./components";
export type {
  ChoiceExerciseProps,
  ExerciseFeedbackProps,
  ExerciseRendererProps,
  FillBlankExerciseProps,
  MatchingExerciseProps,
  ModuleCardProps,
  TextAnswerExerciseProps,
  TrainingSessionProps,
} from "./components";
export { ExerciseRepositoryError, LocalExerciseRepository } from "./data";
export type { ExerciseQuery, ExerciseRepository, ExerciseRepositoryErrorCode } from "./data";
export {
  ANSWER_REASON_CODES,
  CheckerRegistry,
  CheckerRegistryError,
  EXERCISE_DIFFICULTIES,
  EXERCISE_SCHEMA_VERSION,
  ModuleRegistry,
  ModuleRegistryError,
  TRAINING_SESSION_MODES,
  TRAINING_SESSION_SCHEMA_VERSION,
  TRAINING_SESSION_STATUSES,
  TrainingSessionError,
  createTrainingSession,
  evaluateAnswer,
  normalizeAnswer,
  seededShuffle,
  selectCurrentAttempt,
  selectCurrentExercise,
  selectCurrentExerciseId,
  selectHasAnsweredCurrent,
  selectMistakeExerciseIds,
  selectProgress,
  selectPublishedModules,
  selectPublishedTopics,
  selectResultSummary,
  selectScoreSummary,
  submitTrainingAnswer,
  trainingSessionReducer,
} from "./domain";
export type {
  AcceptedAnswer,
  AnswerEvaluation,
  AnswerReasonCode,
  AnswerSubmission,
  ChoiceAnswerEvaluation,
  ChoiceAnswerSubmission,
  ChoiceCorrectAnswer,
  ChoiceExercise,
  CorrectAnswerSnapshot,
  Exercise,
  ExerciseDifficulty,
  ExerciseOption,
  ExerciseSchemaVersion,
  ExerciseScoring,
  ExerciseText,
  FillBlankAnswerEvaluation,
  FillBlankAnswerItem,
  FillBlankAnswerSubmission,
  FillBlankCorrectAnswer,
  FillBlankDefinition,
  FillBlankExercise,
  FillBlankItemResult,
  FreeResponseAnswerEvaluation,
  FreeResponseAnswerSubmission,
  FreeResponseCorrectAnswer,
  FreeResponseExercise,
  HonorificChoiceExercise,
  MatchingAnswerEvaluation,
  MatchingAnswerItem,
  MatchingAnswerSubmission,
  MatchingCorrectAnswer,
  MatchingExercise,
  MatchingHonorificExercise,
  MatchingItemResult,
  MatchingPair,
  MatchingTranslationExercise,
  MeaningChoiceExercise,
  ModuleRegistryErrorCode,
  PlainChoiceExercise,
  TrainingAttemptSnapshot,
  TrainingSessionAction,
  TrainingSessionConfig,
  TrainingSessionContentSnapshot,
  TrainingSessionErrorCode,
  TrainingSessionMode,
  TrainingSessionProgress,
  TrainingSessionResultSummary,
  TrainingSessionSchemaVersion,
  TrainingSessionScoreSummary,
  TrainingSessionState,
  TrainingSessionStatus,
} from "./domain";
export {
  DEMO_TRAINING_MODULE_SLUG,
  DEMO_TRAINING_SEED,
  DEMO_TRAINING_SESSION_ID,
} from "./sessionConstants";
export { useTrainingSession } from "./hooks/useTrainingSession";
export type {
  AnswerDraft,
  ChoiceAnswerDraft,
  FillBlankAnswerDraft,
  FreeResponseAnswerDraft,
  MatchingAnswerDraft,
  UseTrainingSessionOptions,
  UseTrainingSessionResult,
} from "./hooks/useTrainingSession";
export {
  describeFillBlankTemplate,
  parseFillBlankTemplate,
  toExerciseTextView,
  toExerciseView,
} from "./presentation";
export type {
  ChoiceExerciseView,
  ChoiceOptionView,
  ExerciseTextView,
  ExerciseView,
  FillBlankExerciseView,
  FillBlankTemplateSegment,
  FreeResponseExerciseView,
  MatchingExerciseView,
  MatchingLeftItemView,
  MatchingRightOptionView,
  ToExerciseViewOptions,
} from "./presentation";
