import type { ChoiceExercise, ClozeExercise } from "@/lib/types";

export type GrammarExercise = (ClozeExercise & { kind: "cloze" }) | (ChoiceExercise & { kind: "choice" });

export const grammarExercises: GrammarExercise[] = [
  {
    kind: "cloze",
    id: "ex-g-imnida-1",
    sentenceKo: "저는 학생{{blank}}.",
    answer: "입니다",
    options: ["입니다", "입니까", "이에요", "예요"],
    translationRu: "Я студент. (форм.)",
    relatedGrammarId: "g-n-imnida",
    topicId: "u01",
  },
  {
    kind: "choice",
    id: "ex-g-imnida-2",
    promptRu: "Выберите вопрос «Вы учитель?» в формальном стиле.",
    options: ["선생님입니다", "선생님입니까?", "선생님이에요?", "선생님도"],
    answer: "선생님입니까?",
    relatedGrammarId: "g-n-imnida",
    topicId: "u01",
  },
  {
    kind: "cloze",
    id: "ex-g-iga-1",
    sentenceKo: "책{{blank}} 있어요.",
    answer: "이",
    options: ["이", "가", "은", "를"],
    translationRu: "Есть книга.",
    relatedGrammarId: "g-i-ga",
    topicId: "u01",
  },
  {
    kind: "cloze",
    id: "ex-g-eunneun-1",
    sentenceKo: "저{{blank}} 민수입니다.",
    answer: "는",
    options: ["는", "가", "를", "도"],
    translationRu: "Я — Минсу.",
    relatedGrammarId: "g-eun-neun-1",
    topicId: "u01",
  },
  {
    kind: "cloze",
    id: "ex-g-anida-1",
    sentenceKo: "한국 사람이 {{blank}}.",
    answer: "아니에요",
    options: ["아니에요", "이에요", "있어요", "없어요"],
    translationRu: "Я не кореец.",
    relatedGrammarId: "g-i-ga-anida",
    topicId: "u01",
  },
  {
    kind: "cloze",
    id: "ex-g-do-1",
    sentenceKo: "저{{blank}} 학생이에요.",
    answer: "도",
    options: ["도", "는", "가", "만"],
    translationRu: "Я тоже студент.",
    relatedGrammarId: "g-do",
    topicId: "u01",
  },
  {
    kind: "choice",
    id: "ex-g-igeujeo-1",
    promptRu: "Предмет рядом с вами. Какое указательное слово?",
    options: ["이", "그", "저", "의"],
    answer: "이",
    relatedGrammarId: "g-i-geu-jeo",
    topicId: "u02",
  },
  {
    kind: "cloze",
    id: "ex-g-ui-1",
    sentenceKo: "친구{{blank}} 가방이에요.",
    answer: "의",
    options: ["의", "에", "에서", "을"],
    translationRu: "Это сумка друга.",
    relatedGrammarId: "g-ui",
    topicId: "u02",
  },
  {
    kind: "cloze",
    id: "ex-g-e1-1",
    sentenceKo: "학교{{blank}} 있어요.",
    answer: "에",
    options: ["에", "에서", "을", "와"],
    translationRu: "Я в школе.",
    relatedGrammarId: "g-e-1",
    topicId: "u02",
  },
  {
    kind: "cloze",
    id: "ex-g-itda-1",
    sentenceKo: "교실에 학생이 {{blank}}.",
    answer: "있어요",
    options: ["있어요", "없어요", "이에요", "가요"],
    translationRu: "В классе есть студенты.",
    relatedGrammarId: "g-itda-eopda",
    topicId: "u02",
  },
  {
    kind: "cloze",
    id: "ex-g-eulreul-1",
    sentenceKo: "한국어{{blank}} 공부해요.",
    answer: "를",
    options: ["를", "을", "이", "에"],
    translationRu: "Изучаю корейский.",
    relatedGrammarId: "g-eul-reul",
    topicId: "u03",
  },
  {
    kind: "cloze",
    id: "ex-g-man-1",
    sentenceKo: "물{{blank}} 주세요.",
    answer: "만",
    options: ["만", "도", "을", "에"],
    translationRu: "Только воду, пожалуйста.",
    relatedGrammarId: "g-man",
    topicId: "u03",
  },
  {
    kind: "cloze",
    id: "ex-g-eseo-1",
    sentenceKo: "도서관{{blank}} 공부해요.",
    answer: "에서",
    options: ["에서", "에", "으로", "와"],
    translationRu: "Учусь в библиотеке.",
    relatedGrammarId: "g-eseo",
    topicId: "u04",
  },
  {
    kind: "choice",
    id: "ex-g-ayo-1",
    promptRu: "Разговорная форма от 가다:",
    options: ["가요", "갑니다", "갔어", "가십시오"],
    answer: "가요",
    relatedGrammarId: "g-ayo-1",
    topicId: "u05",
  },
  {
    kind: "cloze",
    id: "ex-g-ieyo-1",
    sentenceKo: "의사{{blank}}.",
    answer: "예요",
    options: ["예요", "이에요", "입니다", "이세요"],
    translationRu: "Я врач.",
    relatedGrammarId: "g-ieyo",
    topicId: "u05",
  },
  {
    kind: "cloze",
    id: "ex-g-buteo-1",
    sentenceKo: "아홉 시{{blank}} 다섯 시까지 일해요.",
    answer: "부터",
    options: ["부터", "까지", "에", "에서"],
    translationRu: "Работаю с 9 до 5.",
    relatedGrammarId: "g-buteo-kkaji",
    topicId: "u05",
  },
  {
    kind: "cloze",
    id: "ex-g-an-1",
    sentenceKo: "오늘 학교{{blank}} 가요.",
    answer: "안",
    options: ["안", "못", "도", "만"],
    translationRu: "Сегодня в школу не иду.",
    relatedGrammarId: "g-an-ji-anta",
    topicId: "u05",
  },
  {
    kind: "cloze",
    id: "ex-g-asseot-1",
    sentenceKo: "어제 영화를 {{blank}}.",
    answer: "봤어요",
    options: ["봤어요", "봐요", "볼 거예요", "보세요"],
    translationRu: "Вчера смотрел кино.",
    relatedGrammarId: "g-asseot",
    topicId: "u06",
  },
  {
    kind: "cloze",
    id: "ex-g-go-1",
    sentenceKo: "밥을 먹{{blank}} 공부해요.",
    answer: "고",
    options: ["고", "서", "면", "지만"],
    translationRu: "Ем и учусь.",
    relatedGrammarId: "g-go-1",
    topicId: "u06",
  },
  {
    kind: "cloze",
    id: "ex-g-aboda-1",
    sentenceKo: "한국 음식을 먹어 {{blank}}.",
    answer: "봤어요",
    options: ["봤어요", "있어요", "가요", "싶어요"],
    translationRu: "Пробовал корейскую еду.",
    relatedGrammarId: "g-a-boda",
    topicId: "u06",
  },
  {
    kind: "choice",
    id: "ex-g-birreg-1",
    promptRu: "Правильная форма 덥다 в -아/어요:",
    options: ["더워요", "덥어요", "덥아요", "더어요"],
    answer: "더워요",
    relatedGrammarId: "g-b-irregular",
    topicId: "u07",
  },
  {
    kind: "cloze",
    id: "ex-g-euro-1",
    sentenceKo: "버스{{blank}} 가요.",
    answer: "로",
    options: ["로", "에", "에서", "을"],
    translationRu: "Еду на автобусе.",
    relatedGrammarId: "g-euro-1",
    topicId: "u07",
  },
  {
    kind: "cloze",
    id: "ex-g-ureo-1",
    sentenceKo: "밥을 먹으{{blank}} 식당에 가요.",
    answer: "러",
    options: ["러", "려고", "면", "고"],
    translationRu: "Иду в ресторан поесть.",
    relatedGrammarId: "g-ureo-gada",
    topicId: "u07",
  },
  {
    kind: "cloze",
    id: "ex-g-geoyeyo-1",
    sentenceKo: "내일 공부할 {{blank}}.",
    answer: "거예요",
    options: ["거예요", "게요", "까요", "세요"],
    translationRu: "Завтра буду учиться.",
    relatedGrammarId: "g-eul-geoyeyo-1",
    topicId: "u08",
  },
  {
    kind: "cloze",
    id: "ex-g-jeone-1",
    sentenceKo: "자기 {{blank}} 책을 읽어요.",
    answer: "전에",
    options: ["전에", "후에", "동안", "부터"],
    translationRu: "Перед сном читаю книгу.",
    relatedGrammarId: "g-gi-jeone",
    topicId: "u08",
  },
  {
    kind: "cloze",
    id: "ex-g-useyo-1",
    sentenceKo: "여기 앉으{{blank}}.",
    answer: "세요",
    options: ["세요", "ㅂ니다", "ㄹ까요", "겠어요"],
    translationRu: "Садитесь сюда.",
    relatedGrammarId: "g-useyo",
    topicId: "u09",
  },
  {
    kind: "cloze",
    id: "ex-g-goitda-1",
    sentenceKo: "지금 공부하고 {{blank}}.",
    answer: "있어요",
    options: ["있어요", "없어요", "싶어요", "봐요"],
    translationRu: "Сейчас учусь.",
    relatedGrammarId: "g-go-itda-1",
    topicId: "u09",
  },
  {
    kind: "cloze",
    id: "ex-g-eulkkayo-1",
    sentenceKo: "같이 먹을{{blank}}?",
    answer: "까요",
    options: ["까요", "게요", "거예요", "세요"],
    translationRu: "Поедим вместе?",
    relatedGrammarId: "g-eulkkayo-1",
    topicId: "u10",
  },
  {
    kind: "cloze",
    id: "ex-g-gosipda-1",
    sentenceKo: "김치를 먹고 {{blank}}.",
    answer: "싶어요",
    options: ["싶어요", "있어요", "봐요", "주세요"],
    translationRu: "Хочу есть кимчи.",
    relatedGrammarId: "g-go-sipda",
    topicId: "u10",
  },
  {
    kind: "cloze",
    id: "ex-g-juda-1",
    sentenceKo: "전화해 {{blank}}.",
    answer: "주세요",
    options: ["주세요", "보세요", "싶어요", "가요"],
    translationRu: "Позвоните, пожалуйста.",
    relatedGrammarId: "g-a-juda",
    topicId: "u11",
  },
  {
    kind: "cloze",
    id: "ex-g-umyeon-1",
    sentenceKo: "시간이 있으{{blank}} 만나요.",
    answer: "면",
    options: ["면", "니까", "서", "고"],
    translationRu: "Если будет время — встретимся.",
    relatedGrammarId: "g-umyeon",
    topicId: "u11",
  },
  {
    kind: "cloze",
    id: "ex-g-suitda-1",
    sentenceKo: "오늘 만날 수 {{blank}}.",
    answer: "없어요",
    options: ["없어요", "있어요", "싶어요", "해요"],
    translationRu: "Сегодня не могу встретиться.",
    relatedGrammarId: "g-eul-su-itda",
    topicId: "u12",
  },
  {
    kind: "cloze",
    id: "ex-g-eulgeyo-1",
    sentenceKo: "내일 전화할{{blank}}.",
    answer: "게요",
    options: ["게요", "거예요", "까요", "세요"],
    translationRu: "Завтра позвоню.",
    relatedGrammarId: "g-eulgeyo",
    topicId: "u12",
  },
  {
    kind: "cloze",
    id: "ex-g-mot-1",
    sentenceKo: "오늘 {{blank}} 가요.",
    answer: "못",
    options: ["못", "안", "도", "만"],
    translationRu: "Сегодня не могу пойти.",
    relatedGrammarId: "g-mot",
    topicId: "u13",
  },
  {
    kind: "cloze",
    id: "ex-g-ayadoeda-1",
    sentenceKo: "일찍 일어나야 {{blank}}.",
    answer: "해요",
    options: ["해요", "돼요?", "말아요", "싶어요"],
    translationRu: "Нужно рано встать.",
    relatedGrammarId: "g-aya-doeda",
    topicId: "u14",
  },
  {
    kind: "cloze",
    id: "ex-g-jimal-1",
    sentenceKo: "늦게 오지 {{blank}}.",
    answer: "마세요",
    options: ["마세요", "보세요", "주세요", "싶어요"],
    translationRu: "Не приходите поздно.",
    relatedGrammarId: "g-ji-malda",
    topicId: "u14",
  },
  {
    kind: "cloze",
    id: "ex-g-adodoeda-1",
    sentenceKo: "들어가도 {{blank}}?",
    answer: "돼요",
    options: ["돼요", "안 돼요", "해요", "가요"],
    translationRu: "Можно войти?",
    relatedGrammarId: "g-ado-doeda",
    topicId: "u15",
  },
  {
    kind: "cloze",
    id: "ex-g-umyeonandoeda-1",
    sentenceKo: "술을 마시면 {{blank}}.",
    answer: "안 돼요",
    options: ["안 돼요", "돼요", "해요", "싶어요"],
    translationRu: "Нельзя пить алкоголь.",
    relatedGrammarId: "g-umyeon-an-doeda",
    topicId: "u15",
  },
  {
    kind: "cloze",
    id: "ex-g-eunde-1",
    sentenceKo: "저는 학생{{blank}} 아르바이트해요.",
    answer: "인데",
    options: ["인데", "이면", "이니까", "이고"],
    translationRu: "Я студент, и подрабатываю.",
    relatedGrammarId: "g-eunde",
    topicId: "u16",
  },
  {
    kind: "cloze",
    id: "ex-g-kke-1",
    sentenceKo: "할아버지{{blank}} 선물을 드려요.",
    answer: "께",
    options: ["께", "에게", "한테", "에"],
    translationRu: "Дарю подарок дедушке.",
    relatedGrammarId: "g-kke",
    topicId: "u16",
  },
];

export const vocabClozes: ClozeExercise[] = [
  {
    id: "vc-greet-1",
    sentenceKo: "{{blank}}. 만나서 반가워요.",
    answer: "안녕하세요",
    options: ["안녕하세요", "감사합니다", "죄송합니다", "괜찮아요"],
    translationRu: "Здравствуйте. Рад познакомиться.",
    domainId: "greetings",
    relatedVocabIds: ["v-annyeonghaseyo"],
    topicId: "u01",
  },
  {
    id: "vc-greet-2",
    sentenceKo: "저는 {{blank}}이에요.",
    answer: "학생",
    options: ["학생", "책", "학교", "가방"],
    translationRu: "Я студент.",
    domainId: "greetings",
    relatedVocabIds: ["v-haksaeng"],
    topicId: "u01",
  },
  {
    id: "vc-greet-3",
    sentenceKo: "{{blank}}이 뭐예요?",
    answer: "이름",
    options: ["이름", "시간", "날씨", "음식"],
    translationRu: "Как вас зовут?",
    domainId: "greetings",
    relatedVocabIds: ["v-ireum"],
    topicId: "u01",
  },
  {
    id: "vc-greet-4",
    sentenceKo: "이 사람은 제 {{blank}}예요.",
    answer: "친구",
    options: ["친구", "책상", "버스", "비"],
    translationRu: "Это мой друг.",
    domainId: "greetings",
    relatedVocabIds: ["v-chingu"],
    topicId: "u01",
  },
  {
    id: "vc-greet-5",
    sentenceKo: "{{blank}}에서 왔어요.",
    answer: "한국",
    options: ["한국", "교실", "약국", "택시"],
    translationRu: "Я из Кореи.",
    domainId: "greetings",
    relatedVocabIds: ["v-hanguk"],
    topicId: "u01",
  },
  {
    id: "vc-class-1",
    sentenceKo: "{{blank}}이 책상 위에 있어요.",
    answer: "책",
    options: ["책", "비", "버스", "약"],
    translationRu: "Книга на парте.",
    domainId: "classroom",
    relatedVocabIds: ["v-chaek"],
    topicId: "u02",
  },
  {
    id: "vc-class-2",
    sentenceKo: "{{blank}}에 앉으세요.",
    answer: "의자",
    options: ["의자", "창문", "칠판", "지도"],
    translationRu: "Садитесь на стул.",
    domainId: "classroom",
    relatedVocabIds: ["v-uija"],
    topicId: "u02",
  },
  {
    id: "vc-class-3",
    sentenceKo: "{{blank}}을 주세요.",
    answer: "볼펜",
    options: ["볼펜", "화장실", "지하철", "김치"],
    translationRu: "Дайте ручку.",
    domainId: "classroom",
    relatedVocabIds: ["v-bolpen"],
    topicId: "u02",
  },
  {
    id: "vc-class-4",
    sentenceKo: "{{blank}}을 보세요.",
    answer: "칠판",
    options: ["칠판", "기숙사", "택시", "라면"],
    translationRu: "Смотрите на доску.",
    domainId: "classroom",
    relatedVocabIds: ["v-chilpan"],
    topicId: "u02",
  },
  {
    id: "vc-class-5",
    sentenceKo: "{{blank}}이 넓어요.",
    answer: "교실",
    options: ["교실", "날씨", "가격", "감기"],
    translationRu: "Класс просторный.",
    domainId: "classroom",
    relatedVocabIds: ["v-gyosil"],
    topicId: "u02",
  },
  {
    id: "vc-school-1",
    sentenceKo: "{{blank}}에서 공부해요.",
    answer: "도서관",
    options: ["도서관", "약국", "택시", "김치"],
    translationRu: "Учусь в библиотеке.",
    domainId: "school",
    relatedVocabIds: ["v-doseogwan"],
    topicId: "u02",
  },
  {
    id: "vc-school-2",
    sentenceKo: "{{blank}}이 어디에 있어요?",
    answer: "화장실",
    options: ["화장실", "불고기", "월요일", "바람"],
    translationRu: "Где туалет?",
    domainId: "school",
    relatedVocabIds: ["v-hwajangsil"],
    topicId: "u02",
  },
  {
    id: "vc-school-3",
    sentenceKo: "{{blank}}으로 가세요.",
    answer: "왼쪽",
    options: ["왼쪽", "김치", "선물", "열"],
    translationRu: "Идите налево.",
    domainId: "school",
    relatedVocabIds: ["v-oenjjok"],
    topicId: "u02",
  },
  {
    id: "vc-school-4",
    sentenceKo: "학교 {{blank}}에 있어요.",
    answer: "앞",
    options: ["앞", "약", "눈", "차"],
    translationRu: "Перед школой.",
    domainId: "school",
    relatedVocabIds: ["v-ap"],
    topicId: "u02",
  },
  {
    id: "vc-school-5",
    sentenceKo: "{{blank}}에 살아요.",
    answer: "기숙사",
    options: ["기숙사", "비빔밥", "금요일", "주사"],
    translationRu: "Живу в общежитии.",
    domainId: "school",
    relatedVocabIds: ["v-gigye"],
    topicId: "u02",
  },
  {
    id: "vc-study-1",
    sentenceKo: "한국어를 {{blank}}.",
    answer: "공부해요",
    options: ["공부해요", "기다려요", "끊어요", "타요"],
    translationRu: "Учу корейский.",
    domainId: "school-life",
    relatedVocabIds: ["v-gongbu"],
    topicId: "u03",
  },
  {
    id: "vc-study-2",
    sentenceKo: "{{blank}}가 많아요.",
    answer: "숙제",
    options: ["숙제", "택시", "바람", "카드"],
    translationRu: "Много домашки.",
    domainId: "school-life",
    relatedVocabIds: ["v-sukje"],
    topicId: "u03",
  },
  {
    id: "vc-study-3",
    sentenceKo: "내일 {{blank}}이 있어요.",
    answer: "시험",
    options: ["시험", "정류장", "불고기", "눈"],
    translationRu: "Завтра экзамен.",
    domainId: "school-life",
    relatedVocabIds: ["v-siheom"],
    topicId: "u03",
  },
  {
    id: "vc-study-4",
    sentenceKo: "책을 {{blank}}.",
    answer: "읽어요",
    options: ["읽어요", "타요", "사요", "아파요"],
    translationRu: "Читаю книгу.",
    domainId: "school-life",
    relatedVocabIds: ["v-ilkda"],
    topicId: "u03",
  },
  {
    id: "vc-study-5",
    sentenceKo: "이 문법이 {{blank}}.",
    answer: "어려워요",
    options: ["어려워요", "매워요", "싸요", "멀어요"],
    translationRu: "Эта грамматика трудная.",
    domainId: "school-life",
    relatedVocabIds: ["v-eoryeopda"],
    topicId: "u03",
  },
  {
    id: "vc-daily-1",
    sentenceKo: "{{blank}}에 가요.",
    answer: "집",
    options: ["집", "비", "열", "형"],
    translationRu: "Иду домой.",
    domainId: "daily",
    relatedVocabIds: ["v-jip"],
    topicId: "u04",
  },
  {
    id: "vc-daily-2",
    sentenceKo: "일곱 시에 {{blank}}.",
    answer: "일어나요",
    options: ["일어나요", "끊어요", "내려요", "주문해요"],
    translationRu: "Встаю в семь.",
    domainId: "daily",
    relatedVocabIds: ["v-ireonada"],
    topicId: "u05",
  },
  {
    id: "vc-daily-3",
    sentenceKo: "물을 {{blank}}.",
    answer: "마셔요",
    options: ["마셔요", "입어요", "타요", "기다려요"],
    translationRu: "Пью воду.",
    domainId: "daily",
    relatedVocabIds: ["v-masida"],
    topicId: "u05",
  },
  {
    id: "vc-daily-4",
    sentenceKo: "친구를 {{blank}}.",
    answer: "만나요",
    options: ["만나요", "끊어요", "계산해요", "아파요"],
    translationRu: "Встречаю друга.",
    domainId: "daily",
    relatedVocabIds: ["v-mannada"],
    topicId: "u04",
  },
  {
    id: "vc-daily-5",
    sentenceKo: "아침에 {{blank}}.",
    answer: "운동해요",
    options: ["운동해요", "주문해요", "바꾸세요", "멀어요"],
    translationRu: "Утром занимаюсь спортом.",
    domainId: "daily",
    relatedVocabIds: ["v-undong"],
    topicId: "u05",
  },
  {
    id: "vc-time-1",
    sentenceKo: "{{blank}} 뭐 해요?",
    answer: "지금",
    options: ["지금", "얼마", "사이즈", "현금"],
    translationRu: "Что сейчас делаешь?",
    domainId: "time",
    relatedVocabIds: ["v-jigeum"],
    topicId: "u05",
  },
  {
    id: "vc-time-2",
    sentenceKo: "{{blank}}에 커피를 마셔요.",
    answer: "아침",
    options: ["아침", "약국", "지하철", "가족"],
    translationRu: "Утром пью кофе.",
    domainId: "time",
    relatedVocabIds: ["v-achim"],
    topicId: "u05",
  },
  {
    id: "vc-time-3",
    sentenceKo: "{{blank}} 봐요.",
    answer: "내일",
    options: ["내일", "가격", "정류장", "주사"],
    translationRu: "Увидимся завтра.",
    domainId: "time",
    relatedVocabIds: ["v-naeil"],
    topicId: "u05",
  },
  {
    id: "vc-time-4",
    sentenceKo: "{{blank}} 일어나요.",
    answer: "일찍",
    options: ["일찍", "맵게", "싸게", "멀리"],
    translationRu: "Встаю рано.",
    domainId: "time",
    relatedVocabIds: ["v-iljjik"],
    topicId: "u05",
  },
  {
    id: "vc-time-5",
    sentenceKo: "{{blank}} 말하세요.",
    answer: "천천히",
    options: ["천천히", "매워요", "비싸요", "멀어요"],
    translationRu: "Говорите медленнее.",
    domainId: "time",
    relatedVocabIds: ["v-cheoncheonhi"],
    topicId: "u05",
  },
  {
    id: "vc-cal-1",
    sentenceKo: "{{blank}}에 수업이 있어요.",
    answer: "월요일",
    options: ["월요일", "비빔밥", "엘리베이터", "주사"],
    translationRu: "В понедельник есть занятия.",
    domainId: "calendar",
    relatedVocabIds: ["v-woryoil"],
    topicId: "u04",
  },
  {
    id: "vc-cal-2",
    sentenceKo: "{{blank}}에 쉬어요.",
    answer: "토요일",
    options: ["토요일", "불고기", "볼펜", "열"],
    translationRu: "В субботу отдыхаю.",
    domainId: "calendar",
    relatedVocabIds: ["v-toyoil"],
    topicId: "u04",
  },
  {
    id: "vc-cal-3",
    sentenceKo: "{{blank}}이 언제예요?",
    answer: "생일",
    options: ["생일", "사이즈", "정류장", "바람"],
    translationRu: "Когда день рождения?",
    domainId: "calendar",
    relatedVocabIds: ["v-saengil"],
    topicId: "u04",
  },
  {
    id: "vc-cal-4",
    sentenceKo: "오늘은 {{blank}}이에요.",
    answer: "휴일",
    options: ["휴일", "라면", "지우개", "택시"],
    translationRu: "Сегодня выходной.",
    domainId: "calendar",
    relatedVocabIds: ["v-huil"],
    topicId: "u04",
  },
  {
    id: "vc-cal-5",
    sentenceKo: "이번 {{blank}}에 바빠요.",
    answer: "주",
    options: ["주", "약", "눈", "산"],
    translationRu: "На этой неделе занят.",
    domainId: "calendar",
    relatedVocabIds: ["v-ju"],
    topicId: "u04",
  },
  {
    id: "vc-week-1",
    sentenceKo: "{{blank}}에 뭐 했어요?",
    answer: "주말",
    options: ["주말", "약국", "가격", "주사"],
    translationRu: "Что делали на выходных?",
    domainId: "weekend",
    relatedVocabIds: ["v-jumal"],
    topicId: "u06",
  },
  {
    id: "vc-week-2",
    sentenceKo: "{{blank}}를 봤어요.",
    answer: "영화",
    options: ["영화", "열", "형", "약"],
    translationRu: "Смотрел фильм.",
    domainId: "weekend",
    relatedVocabIds: ["v-yeonghwa"],
    topicId: "u06",
  },
  {
    id: "vc-week-3",
    sentenceKo: "공원에서 {{blank}}.",
    answer: "산책해요",
    options: ["산책해요", "끊어요", "계산해요", "아파요"],
    translationRu: "Гуляю в парке.",
    domainId: "weekend",
    relatedVocabIds: ["v-sanbo"],
    topicId: "u06",
  },
  {
    id: "vc-week-4",
    sentenceKo: "{{blank}}에서 만났어요.",
    answer: "카페",
    options: ["카페", "감기", "현금", "주사"],
    translationRu: "Встретились в кафе.",
    domainId: "weekend",
    relatedVocabIds: ["v-kape"],
    topicId: "u06",
  },
  {
    id: "vc-week-5",
    sentenceKo: "{{blank}}를 들어요.",
    answer: "음악",
    options: ["음악", "사이즈", "정류장", "부모님"],
    translationRu: "Слушаю музыку.",
    domainId: "weekend",
    relatedVocabIds: ["v-eumak"],
    topicId: "u06",
  },
  {
    id: "vc-weather-1",
    sentenceKo: "오늘 {{blank}}가 좋아요.",
    answer: "날씨",
    options: ["날씨", "가격", "번호", "가족"],
    translationRu: "Сегодня хорошая погода.",
    domainId: "weather",
    relatedVocabIds: ["v-nalssi"],
    topicId: "u07",
  },
  {
    id: "vc-weather-2",
    sentenceKo: "날씨가 {{blank}}.",
    answer: "더워요",
    options: ["더워요", "매워요", "싸요", "읽어요"],
    translationRu: "Жарко.",
    domainId: "weather",
    relatedVocabIds: ["v-deopda"],
    topicId: "u07",
  },
  {
    id: "vc-weather-3",
    sentenceKo: "{{blank}}가 와요.",
    answer: "비",
    options: ["비", "책", "형", "차"],
    translationRu: "Идёт дождь.",
    domainId: "weather",
    relatedVocabIds: ["v-bi"],
    topicId: "u07",
  },
  {
    id: "vc-weather-4",
    sentenceKo: "하늘이 {{blank}}.",
    answer: "맑아요",
    options: ["맑아요", "매워요", "입어요", "타요"],
    translationRu: "Небо ясное.",
    domainId: "weather",
    relatedVocabIds: ["v-malgda"],
    topicId: "u07",
  },
  {
    id: "vc-weather-5",
    sentenceKo: "겨울이 {{blank}}.",
    answer: "추워요",
    options: ["추워요", "달아요", "싸요", "읽어요"],
    translationRu: "Зимой холодно.",
    domainId: "weather",
    relatedVocabIds: ["v-chupda"],
    topicId: "u07",
  },
  {
    id: "vc-season-1",
    sentenceKo: "{{blank}}에 꽃이 펴요.",
    answer: "봄",
    options: ["봄", "약", "역", "형"],
    translationRu: "Весной цветут цветы.",
    domainId: "seasons",
    relatedVocabIds: ["v-bom"],
    topicId: "u07",
  },
  {
    id: "vc-season-2",
    sentenceKo: "{{blank}}에 수영해요.",
    answer: "여름",
    options: ["여름", "현금", "숙제", "기숙사"],
    translationRu: "Летом плаваю.",
    domainId: "seasons",
    relatedVocabIds: ["v-yeoreum"],
    topicId: "u07",
  },
  {
    id: "vc-season-3",
    sentenceKo: "{{blank}}에 가고 싶어요.",
    answer: "바다",
    options: ["바다", "볼펜", "칠판", "주사"],
    translationRu: "Хочу к морю.",
    domainId: "seasons",
    relatedVocabIds: ["v-bada"],
    topicId: "u07",
  },
  {
    id: "vc-season-4",
    sentenceKo: "좋아하는 {{blank}}이 뭐예요?",
    answer: "계절",
    options: ["계절", "사이즈", "정류장", "휴지"],
    translationRu: "Какое время года любите?",
    domainId: "seasons",
    relatedVocabIds: ["v-gyejeol"],
    topicId: "u07",
  },
  {
    id: "vc-season-5",
    sentenceKo: "{{blank}}에 스키를 타요.",
    answer: "겨울",
    options: ["겨울", "김치", "가방", "번호"],
    translationRu: "Зимой катаюсь на лыжах.",
    domainId: "seasons",
    relatedVocabIds: ["v-gyeoul"],
    topicId: "u07",
  },
  {
    id: "vc-food-1",
    sentenceKo: "{{blank}}를 먹고 싶어요.",
    answer: "김치",
    options: ["김치", "버스", "창문", "열"],
    translationRu: "Хочу кимчи.",
    domainId: "food",
    relatedVocabIds: ["v-kimchi"],
    topicId: "u10",
  },
  {
    id: "vc-food-2",
    sentenceKo: "{{blank}} 하나 주세요.",
    answer: "비빔밥",
    options: ["비빔밥", "지하철", "지우개", "부모님"],
    translationRu: "Один пибимбап, пожалуйста.",
    domainId: "food",
    relatedVocabIds: ["v-bibimbap"],
    topicId: "u10",
  },
  {
    id: "vc-food-3",
    sentenceKo: "정말 {{blank}}!",
    answer: "맛있어요",
    options: ["맛있어요", "비싸요", "멀어요", "아파요"],
    translationRu: "Очень вкусно!",
    domainId: "food",
    relatedVocabIds: ["v-masitda"],
    topicId: "u10",
  },
  {
    id: "vc-food-4",
    sentenceKo: "이 음식은 {{blank}}.",
    answer: "매워요",
    options: ["매워요", "싸요", "읽어요", "타요"],
    translationRu: "Это блюдо острое.",
    domainId: "food",
    relatedVocabIds: ["v-maepda"],
    topicId: "u10",
  },
  {
    id: "vc-food-5",
    sentenceKo: "배가 {{blank}}.",
    answer: "고파요",
    options: ["고파요", "가까워요", "맑아요", "싸요"],
    translationRu: "Я голоден.",
    domainId: "food",
    relatedVocabIds: ["v-baegopuda"],
    topicId: "u10",
  },
  {
    id: "vc-shop-1",
    sentenceKo: "{{blank}}예요?",
    answer: "얼마",
    options: ["얼마", "언제", "어디", "누구"],
    translationRu: "Сколько это стоит?",
    domainId: "shopping",
    relatedVocabIds: ["v-eolma"],
    topicId: "u09",
  },
  {
    id: "vc-shop-2",
    sentenceKo: "너무 {{blank}}.",
    answer: "비싸요",
    options: ["비싸요", "매워요", "읽어요", "기다려요"],
    translationRu: "Слишком дорого.",
    domainId: "shopping",
    relatedVocabIds: ["v-bissada"],
    topicId: "u09",
  },
  {
    id: "vc-shop-3",
    sentenceKo: "{{blank}}을 샀어요.",
    answer: "선물",
    options: ["선물", "정류장", "감기", "바람"],
    translationRu: "Купил подарок.",
    domainId: "shopping",
    relatedVocabIds: ["v-saengil-seonmul"],
    topicId: "u09",
  },
  {
    id: "vc-shop-4",
    sentenceKo: "{{blank}}로 계산해요.",
    answer: "카드",
    options: ["카드", "김치", "교실", "계절"],
    translationRu: "Плачу картой.",
    domainId: "shopping",
    relatedVocabIds: ["v-card"],
    topicId: "u09",
  },
  {
    id: "vc-shop-5",
    sentenceKo: "이 옷이 {{blank}}.",
    answer: "싸요",
    options: ["싸요", "아파요", "끊어요", "타요"],
    translationRu: "Эта одежда дешёвая.",
    domainId: "shopping",
    relatedVocabIds: ["v-ssaeda"],
    topicId: "u09",
  },
  {
    id: "vc-trans-1",
    sentenceKo: "{{blank}}를 타요.",
    answer: "버스",
    options: ["버스", "김치", "숙제", "열"],
    translationRu: "Еду на автобусе.",
    domainId: "transport",
    relatedVocabIds: ["v-bus"],
    topicId: "u13",
  },
  {
    id: "vc-trans-2",
    sentenceKo: "{{blank}}이 빨라요.",
    answer: "지하철",
    options: ["지하철", "김치", "공책", "주사"],
    translationRu: "Метро быстрое.",
    domainId: "transport",
    relatedVocabIds: ["v-jihacheol"],
    topicId: "u13",
  },
  {
    id: "vc-trans-3",
    sentenceKo: "다음 역에서 {{blank}}.",
    answer: "내리세요",
    options: ["내리세요", "드세요", "입으세요", "끊으세요"],
    translationRu: "Выходите на следующей станции.",
    domainId: "transport",
    relatedVocabIds: ["v-naerida"],
    topicId: "u13",
  },
  {
    id: "vc-trans-4",
    sentenceKo: "집이 {{blank}}.",
    answer: "멀어요",
    options: ["멀어요", "매워요", "달아요", "읽어요"],
    translationRu: "Дом далеко.",
    domainId: "transport",
    relatedVocabIds: ["v-meolda"],
    topicId: "u13",
  },
  {
    id: "vc-trans-5",
    sentenceKo: "버스 {{blank}}이 어디예요?",
    answer: "정류장",
    options: ["정류장", "비빔밥", "부모님", "칠판"],
    translationRu: "Где автобусная остановка?",
    domainId: "transport",
    relatedVocabIds: ["v-jeongryujang"],
    topicId: "u13",
  },
  {
    id: "vc-fam-1",
    sentenceKo: "{{blank}}이 네 명이에요.",
    answer: "가족",
    options: ["가족", "가격", "가방", "계절"],
    translationRu: "В семье четыре человека.",
    domainId: "family",
    relatedVocabIds: ["v-gajok"],
    topicId: "u16",
  },
  {
    id: "vc-fam-2",
    sentenceKo: "{{blank}}는 의사예요.",
    answer: "아버지",
    options: ["아버지", "지하철", "볼펜", "라면"],
    translationRu: "Отец — врач.",
    domainId: "family",
    relatedVocabIds: ["v-abeoji"],
    topicId: "u16",
  },
  {
    id: "vc-fam-3",
    sentenceKo: "{{blank}}이 어디예요?",
    answer: "고향",
    options: ["고향", "사이즈", "정류장", "휴지"],
    translationRu: "Откуда вы родом?",
    domainId: "family",
    relatedVocabIds: ["v-gohyang"],
    topicId: "u16",
  },
  {
    id: "vc-fam-4",
    sentenceKo: "{{blank}}과 살아요.",
    answer: "부모님",
    options: ["부모님", "비빔밥", "엘리베이터", "현금"],
    translationRu: "Живу с родителями.",
    domainId: "family",
    relatedVocabIds: ["v-bumonim"],
    topicId: "u16",
  },
  {
    id: "vc-fam-5",
    sentenceKo: "{{blank}}께 전화해요.",
    answer: "할아버지",
    options: ["할아버지", "정류장", "지우개", "불고기"],
    translationRu: "Звоню дедушке.",
    domainId: "family",
    relatedVocabIds: ["v-halabeoji"],
    topicId: "u16",
  },
  {
    id: "vc-health-1",
    sentenceKo: "머리가 {{blank}}.",
    answer: "아파요",
    options: ["아파요", "매워요", "싸요", "타요"],
    translationRu: "Голова болит.",
    domainId: "health",
    relatedVocabIds: ["v-apuda", "v-meori"],
    topicId: "u15",
  },
  {
    id: "vc-health-2",
    sentenceKo: "{{blank}}을 먹어요.",
    answer: "약",
    options: ["약", "산", "역", "형"],
    translationRu: "Принимаю лекарство.",
    domainId: "health",
    relatedVocabIds: ["v-yak"],
    topicId: "u15",
  },
  {
    id: "vc-health-3",
    sentenceKo: "{{blank}}에 걸렸어요.",
    answer: "감기",
    options: ["감기", "가방", "계절", "카드"],
    translationRu: "Простудился.",
    domainId: "health",
    relatedVocabIds: ["v-gamgi"],
    topicId: "u15",
  },
  {
    id: "vc-health-4",
    sentenceKo: "{{blank}}에서 약을 사요.",
    answer: "약국",
    options: ["약국", "교실", "운동장", "카페"],
    translationRu: "Покупаю лекарство в аптеке.",
    domainId: "health",
    relatedVocabIds: ["v-yakguk"],
    topicId: "u15",
  },
  {
    id: "vc-health-5",
    sentenceKo: "너무 {{blank}}.",
    answer: "피곤해요",
    options: ["피곤해요", "맛있어요", "맑아요", "가까워요"],
    translationRu: "Очень устал.",
    domainId: "health",
    relatedVocabIds: ["v-pisagonhada"],
    topicId: "u15",
  },
  {
    id: "vc-phone-1",
    sentenceKo: "나중에 {{blank}}.",
    answer: "전화할게요",
    options: ["전화할게요", "먹을게요", "갈게요", "입을게요"],
    translationRu: "Позвоню позже.",
    domainId: "phone",
    relatedVocabIds: ["v-jeonhwahada"],
    topicId: "u11",
  },
  {
    id: "vc-phone-2",
    sentenceKo: "전화{{blank}}가 뭐예요?",
    answer: "번호",
    options: ["번호", "가격", "계절", "숙제"],
    translationRu: "Какой номер телефона?",
    domainId: "phone",
    relatedVocabIds: ["v-beonho"],
    topicId: "u11",
  },
  {
    id: "vc-phone-3",
    sentenceKo: "{{blank}}만요.",
    answer: "잠깐",
    options: ["잠깐", "천천히", "일찍", "빨리"],
    translationRu: "Минутку.",
    domainId: "phone",
    relatedVocabIds: ["v-jamkkan"],
    topicId: "u11",
  },
  {
    id: "vc-phone-4",
    sentenceKo: "민수 씨로 {{blank}} 주세요.",
    answer: "바꿔",
    options: ["바꿔", "먹어", "읽어", "앉아"],
    translationRu: "Переключите на Минсу.",
    domainId: "phone",
    relatedVocabIds: ["v-bagkuda"],
    topicId: "u11",
  },
  {
    id: "vc-phone-5",
    sentenceKo: "{{blank}} 전화할게요.",
    answer: "다시",
    options: ["다시", "맵게", "싸게", "멀리"],
    translationRu: "Позвоню ещё раз.",
    domainId: "phone",
    relatedVocabIds: ["v-dahsi"],
    topicId: "u11",
  },
  {
    id: "vc-plans-1",
    sentenceKo: "{{blank}}이 있어요?",
    answer: "계획",
    options: ["계획", "김치", "창문", "열"],
    translationRu: "Есть планы?",
    domainId: "plans",
    relatedVocabIds: ["v-gyehoek"],
    topicId: "u08",
  },
  {
    id: "vc-plans-2",
    sentenceKo: "{{blank}} 동안 뭐 할 거예요?",
    answer: "방학",
    options: ["방학", "약국", "볼펜", "택시"],
    translationRu: "Что будете делать на каникулах?",
    domainId: "plans",
    relatedVocabIds: ["v-banghak"],
    topicId: "u08",
  },
  {
    id: "vc-plans-3",
    sentenceKo: "{{blank}}이 있어요.",
    answer: "약속",
    options: ["약속", "비빔밥", "지우개", "바람"],
    translationRu: "У меня встреча.",
    domainId: "plans",
    relatedVocabIds: ["v-yaksok"],
    topicId: "u08",
  },
  {
    id: "vc-plans-4",
    sentenceKo: "수업이 {{blank}}.",
    answer: "끝났어요",
    options: ["끝났어요", "매웠어요", "비쌌어요", "아팠어요"],
    translationRu: "Урок закончился.",
    domainId: "plans",
    relatedVocabIds: ["v-kkeutnada"],
    topicId: "u08",
  },
  {
    id: "vc-plans-5",
    sentenceKo: "수업 {{blank}}에 만나요.",
    answer: "후",
    options: ["후", "약", "산", "눈"],
    translationRu: "Встретимся после урока.",
    domainId: "plans",
    relatedVocabIds: ["v-hu"],
    topicId: "u08",
  },
  {
    id: "vc-people-1",
    sentenceKo: "{{blank}}이 많아요.",
    answer: "사람",
    options: ["사람", "가방", "바람", "카드"],
    translationRu: "Много людей.",
    domainId: "people",
    relatedVocabIds: ["v-saram"],
    topicId: "u01",
  },
  {
    id: "vc-people-2",
    sentenceKo: "제 아버지는 {{blank}}예요.",
    answer: "의사",
    options: ["의사", "김치", "버스", "창문"],
    translationRu: "Мой отец — врач.",
    domainId: "people",
    relatedVocabIds: ["v-uisa"],
    topicId: "u01",
  },
  {
    id: "vc-people-3",
    sentenceKo: "{{blank}}이에요.",
    answer: "회사원",
    options: ["회사원", "정류장", "비빔밥", "지우개"],
    translationRu: "Я офисный работник.",
    domainId: "people",
    relatedVocabIds: ["v-hyeongje"],
    topicId: "u01",
  },
  {
    id: "vc-people-4",
    sentenceKo: "{{blank}}이 뭐예요?",
    answer: "직업",
    options: ["직업", "날씨", "가격", "사이즈"],
    translationRu: "Кто вы по профессии?",
    domainId: "people",
    relatedVocabIds: ["v-ileum-issda"],
    topicId: "u01",
  },
  {
    id: "vc-people-5",
    sentenceKo: "저는 {{blank}}이에요.",
    answer: "대학생",
    options: ["대학생", "지하철", "월요일", "감기"],
    translationRu: "Я студент университета.",
    domainId: "people",
    relatedVocabIds: ["v-daehaksaeng"],
    topicId: "u01",
  },
];

export function getGrammarExercises(grammarId: string): GrammarExercise[] {
  return grammarExercises.filter((e) => e.relatedGrammarId === grammarId);
}

export function getTopicExercises(topicId: string): GrammarExercise[] {
  return grammarExercises.filter((e) => e.topicId === topicId);
}

export function getDomainClozes(domainId: string): ClozeExercise[] {
  return vocabClozes.filter((e) => e.domainId === domainId);
}
