import type { VocabDomain } from "@/lib/types";

export const vocabDomains: VocabDomain[] = [
  {
    id: "greetings",
    titleKo: "인사",
    titleRu: "Приветствия",
    topicIds: ["u01"],
    words: [
      { id: "v-annyeonghaseyo", ko: "안녕하세요", ru: "здравствуйте", examples: [{ ko: "안녕하세요. 만나서 반가워요.", ru: "Здравствуйте. Рад познакомиться." }] },
      { id: "v-annyeonghi-gaseyo", ko: "안녕히 가세요", ru: "до свидания (уходящему)", examples: [{ ko: "안녕히 가세요!", ru: "До свидания!" }] },
      { id: "v-annyeonghi-gyeseyo", ko: "안녕히 계세요", ru: "до свидания (остающемуся)", examples: [{ ko: "저는 이만. 안녕히 계세요.", ru: "Я пойду. Оставайтесь с миром." }] },
      { id: "v-bangawoyo", ko: "반가워요", ru: "рад встрече", examples: [{ ko: "처음 뵙겠습니다. 반가워요.", ru: "Приятно познакомиться." }] },
      { id: "v-ireum", ko: "이름", ru: "имя", examples: [{ ko: "이름이 뭐예요?", ru: "Как вас зовут?" }] },
      { id: "v-haksaeng", ko: "학생", ru: "студент / ученик", examples: [{ ko: "저는 학생이에요.", ru: "Я студент." }] },
      { id: "v-seonsaengnim", ko: "선생님", ru: "учитель", examples: [{ ko: "저분은 선생님이에요.", ru: "Тот человек — учитель." }] },
      { id: "v-hanguk", ko: "한국", ru: "Корея", examples: [{ ko: "한국에서 왔어요.", ru: "Я из Кореи." }] },
      { id: "v-hanguk-saram", ko: "한국 사람", ru: "кореец", examples: [{ ko: "한국 사람이에요?", ru: "Вы кореец?" }] },
      { id: "v-chinjeol", ko: "친절하다", ru: "быть добрым / вежливым", examples: [{ ko: "선생님이 친절해요.", ru: "Учитель добрый." }] },
      { id: "v-mannaseo", ko: "만나서 반갑습니다", ru: "рад знакомству (форм.)", examples: [{ ko: "만나서 반갑습니다.", ru: "Рад знакомству." }] },
      { id: "v-mwo", ko: "뭐", ru: "что (разг.)", examples: [{ ko: "이름이 뭐예요?", ru: "Как зовут?" }] },
      { id: "v-jeo", ko: "저", ru: "я (скромно)", examples: [{ ko: "저는 민수예요.", ru: "Я Минсу." }] },
      { id: "v-uri", ko: "우리", ru: "мы / наш", examples: [{ ko: "우리 학교예요.", ru: "Это наша школа." }] },
      { id: "v-chingu", ko: "친구", ru: "друг", examples: [{ ko: "이 사람은 제 친구예요.", ru: "Это мой друг." }] },
    ],
  },
  {
    id: "people",
    titleKo: "사람",
    titleRu: "Люди и профессии",
    topicIds: ["u01", "u16"],
    words: [
      { id: "v-saram", ko: "사람", ru: "человек", examples: [{ ko: "사람이 많아요.", ru: "Много людей." }] },
      { id: "v-uisa", ko: "의사", ru: "врач", examples: [{ ko: "제 아버지는 의사예요.", ru: "Мой отец — врач." }] },
      { id: "v-hyeongje", ko: "회사원", ru: "офисный работник", examples: [{ ko: "회사원이에요.", ru: "Я офисный работник." }] },
      { id: "v-gongmuwon", ko: "공무원", ru: "госслужащий", examples: [{ ko: "누나는 공무원이에요.", ru: "Старшая сестра — госслужащая." }] },
      { id: "v-yeoja", ko: "여자", ru: "женщина", examples: [{ ko: "저 여자는 친구예요.", ru: "Та женщина — подруга." }] },
      { id: "v-namja", ko: "남자", ru: "мужчина", examples: [{ ko: "그 남자는 선생님이에요.", ru: "Тот мужчина — учитель." }] },
      { id: "v-ai", ko: "아이", ru: "ребёнок", examples: [{ ko: "아이가 귀여워요.", ru: "Ребёнок милый." }] },
      { id: "v-bun", ko: "분", ru: "человек (почтит.)", examples: [{ ko: "저분이 사장님이에요.", ru: "Тот человек — директор." }] },
      { id: "v-ssi", ko: "씨", ru: "господин/госпожа", examples: [{ ko: "민수 씨, 안녕하세요.", ru: "Здравствуйте, Минсу." }] },
      { id: "v-gukjeok", ko: "국적", ru: "гражданство", examples: [{ ko: "국적이 뭐예요?", ru: "Какое у вас гражданство?" }] },
      { id: "v-ileum-issda", ko: "직업", ru: "профессия", examples: [{ ko: "직업이 뭐예요?", ru: "Кто вы по профессии?" }] },
      { id: "v-daehaksaeng", ko: "대학생", ru: "студент вуза", examples: [{ ko: "저는 대학생이에요.", ru: "Я студент университета." }] },
    ],
  },
  {
    id: "classroom",
    titleKo: "교실",
    titleRu: "Класс и предметы",
    topicIds: ["u02"],
    words: [
      { id: "v-chaek", ko: "책", ru: "книга", examples: [{ ko: "책이 책상 위에 있어요.", ru: "Книга на парте." }] },
      { id: "v-gongchaek", ko: "공책", ru: "тетрадь", examples: [{ ko: "공책에 쓰세요.", ru: "Пишите в тетради." }] },
      { id: "v-yeonpil", ko: "연필", ru: "карандаш", examples: [{ ko: "연필이 있어요?", ru: "Есть карандаш?" }] },
      { id: "v-bolpen", ko: "볼펜", ru: "ручка", examples: [{ ko: "볼펜을 주세요.", ru: "Дайте ручку." }] },
      { id: "v-gabang", ko: "가방", ru: "сумка", examples: [{ ko: "가방이 커요.", ru: "Сумка большая." }] },
      { id: "v-chaeksang", ko: "책상", ru: "парта / стол", examples: [{ ko: "책상 아래에 있어요.", ru: "Под партой." }] },
      { id: "v-uija", ko: "의자", ru: "стул", examples: [{ ko: "의자에 앉으세요.", ru: "Садитесь на стул." }] },
      { id: "v-chilpan", ko: "칠판", ru: "доска", examples: [{ ko: "칠판을 보세요.", ru: "Смотрите на доску." }] },
      { id: "v-changmun", ko: "창문", ru: "окно", examples: [{ ko: "창문을 열어 주세요.", ru: "Откройте окно." }] },
      { id: "v-mun", ko: "문", ru: "дверь", examples: [{ ko: "문이 닫혀 있어요.", ru: "Дверь закрыта." }] },
      { id: "v-gyosil", ko: "교실", ru: "класс", examples: [{ ko: "교실이 넓어요.", ru: "Класс просторный." }] },
      { id: "v-jihasi", ko: "지우개", ru: "ластик", examples: [{ ko: "지우개가 필요해요.", ru: "Нужен ластик." }] },
      { id: "v-ja", ko: "자", ru: "линейка", examples: [{ ko: "자로 선을 그어요.", ru: "Черчу линию линейкой." }] },
      { id: "v-sajin", ko: "사진", ru: "фото", examples: [{ ko: "사진을 찍어요.", ru: "Фотографирую." }] },
      { id: "v-jonjae", ko: "지도", ru: "карта", examples: [{ ko: "지도를 봐요.", ru: "Смотрю карту." }] },
    ],
  },
  {
    id: "school",
    titleKo: "학교",
    titleRu: "Школа и здания",
    topicIds: ["u02", "u03"],
    words: [
      { id: "v-hakgyo", ko: "학교", ru: "школа", examples: [{ ko: "학교에 가요.", ru: "Иду в школу." }] },
      { id: "v-doseogwan", ko: "도서관", ru: "библиотека", examples: [{ ko: "도서관에서 공부해요.", ru: "Учусь в библиотеке." }] },
      { id: "v-sikdang", ko: "식당", ru: "столовая / ресторан", examples: [{ ko: "식당이 어디에 있어요?", ru: "Где столовая?" }] },
      { id: "v-hwajangsil", ko: "화장실", ru: "туалет", examples: [{ ko: "화장실이 저기 있어요.", ru: "Туалет там." }] },
      { id: "v-undongjang", ko: "운동장", ru: "спортплощадка", examples: [{ ko: "운동장에서 축구해요.", ru: "Играю в футбол на площадке." }] },
      { id: "v-samusil", ko: "사무실", ru: "офис / кабинет", examples: [{ ko: "사무실에 가세요.", ru: "Идите в кабинет." }] },
      { id: "v-gigye", ko: "기숙사", ru: "общежитие", examples: [{ ko: "기숙사에 살아요.", ru: "Живу в общежитии." }] },
      { id: "v-gyomun", ko: "교문", ru: "ворота школы", examples: [{ ko: "교문 앞에서 만나요.", ru: "Встретимся у ворот." }] },
      { id: "v-elevator", ko: "엘리베이터", ru: "лифт", examples: [{ ko: "엘리베이터를 타요.", ru: "Еду на лифте." }] },
      { id: "v-gyedan", ko: "계단", ru: "лестница", examples: [{ ko: "계단으로 올라가요.", ru: "Поднимаюсь по лестнице." }] },
      { id: "v-ogeunjjok", ko: "오른쪽", ru: "правая сторона", examples: [{ ko: "오른쪽에 있어요.", ru: "Справа." }] },
      { id: "v-oenjjok", ko: "왼쪽", ru: "левая сторона", examples: [{ ko: "왼쪽으로 가세요.", ru: "Идите налево." }] },
      { id: "v-ap", ko: "앞", ru: "перед", examples: [{ ko: "학교 앞에 있어요.", ru: "Перед школой." }] },
      { id: "v-dwi", ko: "뒤", ru: "сзади", examples: [{ ko: "건물 뒤에 있어요.", ru: "За зданием." }] },
      { id: "v-yeope", ko: "옆", ru: "рядом", examples: [{ ko: "도서관 옆에 있어요.", ru: "Рядом с библиотекой." }] },
    ],
  },
  {
    id: "school-life",
    titleKo: "학교생활",
    titleRu: "Учёба",
    topicIds: ["u03"],
    words: [
      { id: "v-gongbu", ko: "공부하다", ru: "учиться", examples: [{ ko: "한국어를 공부해요.", ru: "Учу корейский." }] },
      { id: "v-sueop", ko: "수업", ru: "занятие", examples: [{ ko: "수업이 끝났어요.", ru: "Занятие закончилось." }] },
      { id: "v-sukje", ko: "숙제", ru: "домашнее задание", examples: [{ ko: "숙제가 많아요.", ru: "Много домашки." }] },
      { id: "v-siheom", ko: "시험", ru: "экзамен", examples: [{ ko: "내일 시험이 있어요.", ru: "Завтра экзамен." }] },
      { id: "v-jiruda", ko: "질문하다", ru: "задать вопрос", examples: [{ ko: "질문해도 돼요?", ru: "Можно спросить?" }] },
      { id: "v-dab", ko: "대답하다", ru: "отвечать", examples: [{ ko: "크게 대답하세요.", ru: "Отвечайте громко." }] },
      { id: "v-ilkda", ko: "읽다", ru: "читать", examples: [{ ko: "책을 읽어요.", ru: "Читаю книгу." }] },
      { id: "v-sseuda", ko: "쓰다", ru: "писать", examples: [{ ko: "이름을 쓰세요.", ru: "Напишите имя." }] },
      { id: "v-deutda", ko: "듣다", ru: "слушать", examples: [{ ko: "선생님 말씀을 들어요.", ru: "Слушаю учителя." }] },
      { id: "v-malhada", ko: "말하다", ru: "говорить", examples: [{ ko: "한국어로 말해요.", ru: "Говорю по-корейски." }] },
      { id: "v-iju", ko: "이해하다", ru: "понимать", examples: [{ ko: "이해해요.", ru: "Понимаю." }] },
      { id: "v-eoryeopda", ko: "어렵다", ru: "трудный", examples: [{ ko: "이 문법이 어려워요.", ru: "Эта грамматика трудная." }] },
      { id: "v-swipda", ko: "쉽다", ru: "лёгкий", examples: [{ ko: "숙제가 쉬워요.", ru: "Домашка лёгкая." }] },
      { id: "v-jaemiitda", ko: "재미있다", ru: "интересный", examples: [{ ko: "수업이 재미있어요.", ru: "Урок интересный." }] },
    ],
  },
  {
    id: "daily",
    titleKo: "일상",
    titleRu: "Повседневность",
    topicIds: ["u04", "u05"],
    words: [
      { id: "v-jip", ko: "집", ru: "дом", examples: [{ ko: "집에 가요.", ru: "Иду домой." }] },
      { id: "v-ilhada", ko: "일하다", ru: "работать", examples: [{ ko: "회사에서 일해요.", ru: "Работаю в компании." }] },
      { id: "v-swida", ko: "쉬다", ru: "отдыхать", examples: [{ ko: "주말에 쉬어요.", ru: "В выходные отдыхаю." }] },
      { id: "v-jada", ko: "자다", ru: "спать", examples: [{ ko: "일찍 자요.", ru: "Рано сплю." }] },
      { id: "v-ireonada", ko: "일어나다", ru: "вставать", examples: [{ ko: "일곱 시에 일어나요.", ru: "Встаю в семь." }] },
      { id: "v-bap", ko: "밥", ru: "рис / еда", examples: [{ ko: "밥을 먹어요.", ru: "Ем." }] },
      { id: "v-meokda", ko: "먹다", ru: "есть", examples: [{ ko: "빵을 먹어요.", ru: "Ем хлеб." }] },
      { id: "v-masida", ko: "마시다", ru: "пить", examples: [{ ko: "물을 마셔요.", ru: "Пью воду." }] },
      { id: "v-sada", ko: "사다", ru: "покупать", examples: [{ ko: "과일을 사요.", ru: "Покупаю фрукты." }] },
      { id: "v-boda", ko: "보다", ru: "смотреть / видеть", examples: [{ ko: "텔레비전을 봐요.", ru: "Смотрю телевизор." }] },
      { id: "v-mannada", ko: "만나다", ru: "встречать", examples: [{ ko: "친구를 만나요.", ru: "Встречаю друга." }] },
      { id: "v-gadda", ko: "가다", ru: "идти / ехать", examples: [{ ko: "학교에 가요.", ru: "Иду в школу." }] },
      { id: "v-oda", ko: "오다", ru: "приходить", examples: [{ ko: "집에 와요.", ru: "Прихожу домой." }] },
      { id: "v-undong", ko: "운동하다", ru: "заниматься спортом", examples: [{ ko: "아침에 운동해요.", ru: "Утром занимаюсь спортом." }] },
      { id: "v-ssawo", ko: "샤워하다", ru: "принимать душ", examples: [{ ko: "샤워하고 자요.", ru: "Принимаю душ и сплю." }] },
    ],
  },
  {
    id: "time",
    titleKo: "시간",
    titleRu: "Время",
    topicIds: ["u05"],
    words: [
      { id: "v-sigan", ko: "시간", ru: "время / час", examples: [{ ko: "시간이 있어요?", ru: "Есть время?" }] },
      { id: "v-si", ko: "시", ru: "час", examples: [{ ko: "세 시예요.", ru: "Три часа." }] },
      { id: "v-bun", ko: "분", ru: "минута", examples: [{ ko: "십 분 기다려 주세요.", ru: "Подождите 10 минут." }] },
      { id: "v-achim", ko: "아침", ru: "утро / завтрак", examples: [{ ko: "아침에 커피를 마셔요.", ru: "Утром пью кофе." }] },
      { id: "v-jeomsim", ko: "점심", ru: "обед", examples: [{ ko: "점심을 먹었어요.", ru: "Пообедал." }] },
      { id: "v-jeonyeok", ko: "저녁", ru: "вечер / ужин", examples: [{ ko: "저녁에 만나요.", ru: "Встретимся вечером." }] },
      { id: "v-bam", ko: "밤", ru: "ночь", examples: [{ ko: "밤에 공부해요.", ru: "Учусь ночью." }] },
      { id: "v-oneul", ko: "오늘", ru: "сегодня", examples: [{ ko: "오늘은 바빠요.", ru: "Сегодня занят." }] },
      { id: "v-naeil", ko: "내일", ru: "завтра", examples: [{ ko: "내일 봐요.", ru: "Увидимся завтра." }] },
      { id: "v-eoje", ko: "어제", ru: "вчера", examples: [{ ko: "어제 영화 봤어요.", ru: "Вчера смотрел кино." }] },
      { id: "v-jigeum", ko: "지금", ru: "сейчас", examples: [{ ko: "지금 뭐 해요?", ru: "Что сейчас делаешь?" }] },
      { id: "v-iljjik", ko: "일찍", ru: "рано", examples: [{ ko: "일찍 일어나요.", ru: "Встаю рано." }] },
      { id: "v-neuje", ko: "늦게", ru: "поздно", examples: [{ ko: "늦게 잤어요.", ru: "Лёг поздно." }] },
      { id: "v-ppalli", ko: "빨리", ru: "быстро", examples: [{ ko: "빨리 오세요.", ru: "Приходите скорее." }] },
      { id: "v-cheoncheonhi", ko: "천천히", ru: "медленно", examples: [{ ko: "천천히 말하세요.", ru: "Говорите медленнее." }] },
    ],
  },
  {
    id: "calendar",
    titleKo: "요일",
    titleRu: "Дни и календарь",
    topicIds: ["u04"],
    words: [
      { id: "v-woryoil", ko: "월요일", ru: "понедельник", examples: [{ ko: "월요일에 수업이 있어요.", ru: "В понедельник есть занятия." }] },
      { id: "v-hwayoil", ko: "화요일", ru: "вторник", examples: [{ ko: "화요일에 만나요.", ru: "Встретимся во вторник." }] },
      { id: "v-suyoil", ko: "수요일", ru: "среда", examples: [{ ko: "수요일은 바빠요.", ru: "В среду занят." }] },
      { id: "v-mogyoil", ko: "목요일", ru: "четверг", examples: [{ ko: "목요일에 시험이 있어요.", ru: "В четверг экзамен." }] },
      { id: "v-geumyoil", ko: "금요일", ru: "пятница", examples: [{ ko: "금요일에 파티가 있어요.", ru: "В пятницу вечеринка." }] },
      { id: "v-toyoil", ko: "토요일", ru: "суббота", examples: [{ ko: "토요일에 쉬어요.", ru: "В субботу отдыхаю." }] },
      { id: "v-iryoil", ko: "일요일", ru: "воскресенье", examples: [{ ko: "일요일에 교회에 가요.", ru: "В воскресенье иду в церковь." }] },
      { id: "v-ju", ko: "주", ru: "неделя", examples: [{ ko: "이번 주에 바빠요.", ru: "На этой неделе занят." }] },
      { id: "v-dal", ko: "달", ru: "месяц", examples: [{ ko: "다음 달에 여행해요.", ru: "В следующем месяце путешествую." }] },
      { id: "v-nyeon", ko: "년", ru: "год", examples: [{ ko: "내년에 졸업해요.", ru: "В следующем году выпускаюсь." }] },
      { id: "v-saengil", ko: "생일", ru: "день рождения", examples: [{ ko: "생일이 언제예요?", ru: "Когда день рождения?" }] },
      { id: "v-huil", ko: "휴일", ru: "выходной / праздник", examples: [{ ko: "오늘은 휴일이에요.", ru: "Сегодня выходной." }] },
    ],
  },
  {
    id: "weekend",
    titleKo: "주말",
    titleRu: "Выходные и досуг",
    topicIds: ["u06"],
    words: [
      { id: "v-jumal", ko: "주말", ru: "выходные", examples: [{ ko: "주말에 뭐 했어요?", ru: "Что делали на выходных?" }] },
      { id: "v-yeonghwa", ko: "영화", ru: "фильм", examples: [{ ko: "영화를 봤어요.", ru: "Смотрел фильм." }] },
      { id: "v-eumak", ko: "음악", ru: "музыка", examples: [{ ko: "음악을 들어요.", ru: "Слушаю музыку." }] },
      { id: "v-sanbo", ko: "산책하다", ru: "гулять", examples: [{ ko: "공원에서 산책해요.", ru: "Гуляю в парке." }] },
      { id: "v-yeohaeng", ko: "여행하다", ru: "путешествовать", examples: [{ ko: "부산에 여행했어요.", ru: "Путешествовал в Пусан." }] },
      { id: "v-shopping", ko: "쇼핑하다", ru: "ходить по магазинам", examples: [{ ko: "백화점에서 쇼핑해요.", ru: "Шопинг в универмаге." }] },
      { id: "v-chukgu", ko: "축구", ru: "футбол", examples: [{ ko: "축구를 해요.", ru: "Играю в футбол." }] },
      { id: "v-nolae", ko: "노래", ru: "песня", examples: [{ ko: "노래를 불러요.", ru: "Пою песню." }] },
      { id: "v-geim", ko: "게임", ru: "игра", examples: [{ ko: "게임을 했어요.", ru: "Играл в игру." }] },
      { id: "v-gongwon", ko: "공원", ru: "парк", examples: [{ ko: "공원에 갔어요.", ru: "Ходил в парк." }] },
      { id: "v-bang", ko: "방", ru: "комната", examples: [{ ko: "방에서 쉬어요.", ru: "Отдыхаю в комнате." }] },
      { id: "v-kape", ko: "카페", ru: "кафе", examples: [{ ko: "카페에서 만났어요.", ru: "Встретились в кафе." }] },
    ],
  },
  {
    id: "weather",
    titleKo: "날씨",
    titleRu: "Погода",
    topicIds: ["u07"],
    words: [
      { id: "v-nalssi", ko: "날씨", ru: "погода", examples: [{ ko: "오늘 날씨가 좋아요.", ru: "Сегодня хорошая погода." }] },
      { id: "v-deopda", ko: "덥다", ru: "жаркий", examples: [{ ko: "날씨가 더워요.", ru: "Жарко." }] },
      { id: "v-chupda", ko: "춥다", ru: "холодный", examples: [{ ko: "겨울이 추워요.", ru: "Зимой холодно." }] },
      { id: "v-ttatteutada", ko: "따뜻하다", ru: "тёплый", examples: [{ ko: "봄이 따뜻해요.", ru: "Весной тепло." }] },
      { id: "v-siwonhada", ko: "시원하다", ru: "прохладный", examples: [{ ko: "바람이 시원해요.", ru: "Ветер прохладный." }] },
      { id: "v-bi", ko: "비", ru: "дождь", examples: [{ ko: "비가 와요.", ru: "Идёт дождь." }] },
      { id: "v-nun", ko: "눈", ru: "снег / глаз", examples: [{ ko: "눈이 와요.", ru: "Идёт снег." }] },
      { id: "v-baram", ko: "바람", ru: "ветер", examples: [{ ko: "바람이 불어요.", ru: "Дует ветер." }] },
      { id: "v-hae", ko: "해", ru: "солнце", examples: [{ ko: "해가 밝아요.", ru: "Солнце яркое." }] },
      { id: "v-heulida", ko: "흐리다", ru: "пасмурный", examples: [{ ko: "하늘이 흐려요.", ru: "Небо пасмурное." }] },
      { id: "v-malgda", ko: "맑다", ru: "ясный", examples: [{ ko: "하늘이 맑아요.", ru: "Небо ясное." }] },
      { id: "v-seupo", ko: "습하다", ru: "влажный", examples: [{ ko: "날씨가 습해요.", ru: "Влажно." }] },
    ],
  },
  {
    id: "seasons",
    titleKo: "계절",
    titleRu: "Времена года",
    topicIds: ["u07"],
    words: [
      { id: "v-bom", ko: "봄", ru: "весна", examples: [{ ko: "봄에 꽃이 펴요.", ru: "Весной цветут цветы." }] },
      { id: "v-yeoreum", ko: "여름", ru: "лето", examples: [{ ko: "여름에 수영해요.", ru: "Летом плаваю." }] },
      { id: "v-gaeul", ko: "가을", ru: "осень", examples: [{ ko: "가을이 좋아요.", ru: "Люблю осень." }] },
      { id: "v-gyeoul", ko: "겨울", ru: "зима", examples: [{ ko: "겨울에 스키를 타요.", ru: "Зимой катаюсь на лыжах." }] },
      { id: "v-kkot", ko: "꽃", ru: "цветок", examples: [{ ko: "꽃이 예뻐요.", ru: "Цветы красивые." }] },
      { id: "v-suyeong", ko: "수영하다", ru: "плавать", examples: [{ ko: "바다에서 수영해요.", ru: "Плаваю в море." }] },
      { id: "v-san", ko: "산", ru: "гора", examples: [{ ko: "산에 가요.", ru: "Иду в горы." }] },
      { id: "v-bada", ko: "바다", ru: "море", examples: [{ ko: "바다에 가고 싶어요.", ru: "Хочу к морю." }] },
      { id: "v-gyejeol", ko: "계절", ru: "время года", examples: [{ ko: "좋아하는 계절이 뭐예요?", ru: "Какое время года любите?" }] },
      { id: "v-ot", ko: "옷", ru: "одежда", examples: [{ ko: "따뜻한 옷을 입어요.", ru: "Ношу тёплую одежду." }] },
    ],
  },
  {
    id: "food",
    titleKo: "음식",
    titleRu: "Еда",
    topicIds: ["u10"],
    words: [
      { id: "v-eumsik", ko: "음식", ru: "еда", examples: [{ ko: "한국 음식이 맛있어요.", ru: "Корейская еда вкусная." }] },
      { id: "v-kimchi", ko: "김치", ru: "кимчи", examples: [{ ko: "김치를 먹고 싶어요.", ru: "Хочу кимчи." }] },
      { id: "v-bibimbap", ko: "비빔밥", ru: "пибимбап", examples: [{ ko: "비빔밥 하나 주세요.", ru: "Один пибимбап, пожалуйста." }] },
      { id: "v-bulgogi", ko: "불고기", ru: "пульгоги", examples: [{ ko: "불고기가 유명해요.", ru: "Пульгоги знаменитое." }] },
      { id: "v-ramyeon", ko: "라면", ru: "рамен", examples: [{ ko: "라면을 끓여요.", ru: "Варю рамен." }] },
      { id: "v-mul", ko: "물", ru: "вода", examples: [{ ko: "물 좀 주세요.", ru: "Воды, пожалуйста." }] },
      { id: "v-keopi", ko: "커피", ru: "кофе", examples: [{ ko: "커피 한 잔 주세요.", ru: "Чашку кофе, пожалуйста." }] },
      { id: "v-cha", ko: "차", ru: "чай", examples: [{ ko: "녹차를 마셔요.", ru: "Пью зелёный чай." }] },
      { id: "v-bbang", ko: "빵", ru: "хлеб", examples: [{ ko: "빵을 사요.", ru: "Покупаю хлеб." }] },
      { id: "v-gwail", ko: "과일", ru: "фрукты", examples: [{ ko: "과일을 좋아해요.", ru: "Люблю фрукты." }] },
      { id: "v-gogi", ko: "고기", ru: "мясо", examples: [{ ko: "고기를 안 먹어요.", ru: "Не ем мясо." }] },
      { id: "v-saengseon", ko: "생선", ru: "рыба", examples: [{ ko: "생선이 신선해요.", ru: "Рыба свежая." }] },
      { id: "v-masitda", ko: "맛있다", ru: "вкусный", examples: [{ ko: "정말 맛있어요!", ru: "Очень вкусно!" }] },
      { id: "v-maepda", ko: "맵다", ru: "острый", examples: [{ ko: "이 음식은 매워요.", ru: "Это блюдо острое." }] },
      { id: "v-dangda", ko: "달다", ru: "сладкий", examples: [{ ko: "케이크가 달아요.", ru: "Торт сладкий." }] },
      { id: "v-jjonada", ko: "주문하다", ru: "заказывать", examples: [{ ko: "메뉴를 주문해요.", ru: "Заказываю по меню." }] },
      { id: "v-baegopuda", ko: "배고프다", ru: "голодный", examples: [{ ko: "배가 고파요.", ru: "Я голоден." }] },
      { id: "v-baebureuda", ko: "배부르다", ru: "сытый", examples: [{ ko: "배가 불러요.", ru: "Я сыт." }] },
    ],
  },
  {
    id: "shopping",
    titleKo: "쇼핑",
    titleRu: "Покупки",
    topicIds: ["u09"],
    words: [
      { id: "v-gage", ko: "가게", ru: "магазин", examples: [{ ko: "가게에서 사요.", ru: "Покупаю в магазине." }] },
      { id: "v-baekwajeom", ko: "백화점", ru: "универмаг", examples: [{ ko: "백화점에 가요.", ru: "Иду в универмаг." }] },
      { id: "v-gagyeok", ko: "가격", ru: "цена", examples: [{ ko: "가격이 얼마예요?", ru: "Сколько стоит?" }] },
      { id: "v-eolma", ko: "얼마", ru: "сколько (цена)", examples: [{ ko: "얼마예요?", ru: "Сколько это стоит?" }] },
      { id: "v-won", ko: "원", ru: "вона", examples: [{ ko: "만 원이에요.", ru: "10 000 вон." }] },
      { id: "v-ssaeda", ko: "싸다", ru: "дешёвый", examples: [{ ko: "이 옷이 싸요.", ru: "Эта одежда дешёвая." }] },
      { id: "v-bissada", ko: "비싸다", ru: "дорогой", examples: [{ ko: "너무 비싸요.", ru: "Слишком дорого." }] },
      { id: "v-size", ko: "사이즈", ru: "размер", examples: [{ ko: "사이즈가 커요.", ru: "Размер большой." }] },
      { id: "v-saengil-seonmul", ko: "선물", ru: "подарок", examples: [{ ko: "선물을 샀어요.", ru: "Купил подарок." }] },
      { id: "v-card", ko: "카드", ru: "карта", examples: [{ ko: "카드로 계산해요.", ru: "Плачу картой." }] },
      { id: "v-hyeongeum", ko: "현금", ru: "наличные", examples: [{ ko: "현금으로 내요.", ru: "Плачу наличными." }] },
      { id: "v-gyesanhada", ko: "계산하다", ru: "рассчитываться", examples: [{ ko: "여기서 계산해요.", ru: "Оплачиваю здесь." }] },
      { id: "v-pillyohada", ko: "필요하다", ru: "нужный", examples: [{ ko: "이게 필요해요.", ru: "Это нужно." }] },
      { id: "v-ipda", ko: "입다", ru: "надевать (одежду)", examples: [{ ko: "셔츠를 입어요.", ru: "Надеваю рубашку." }] },
    ],
  },
  {
    id: "transport",
    titleKo: "교통",
    titleRu: "Транспорт",
    topicIds: ["u13"],
    words: [
      { id: "v-bus", ko: "버스", ru: "автобус", examples: [{ ko: "버스를 타요.", ru: "Еду на автобусе." }] },
      { id: "v-jihacheol", ko: "지하철", ru: "метро", examples: [{ ko: "지하철이 빨라요.", ru: "Метро быстрое." }] },
      { id: "v-taxi", ko: "택시", ru: "такси", examples: [{ ko: "택시를 불러요.", ru: "Вызываю такси." }] },
      { id: "v-gidarida", ko: "기다리다", ru: "ждать", examples: [{ ko: "정류장에서 기다려요.", ru: "Жду на остановке." }] },
      { id: "v-tada", ko: "타다", ru: "садиться (на транспорт)", examples: [{ ko: "기차를 타요.", ru: "Сажусь на поезд." }] },
      { id: "v-naerida", ko: "내리다", ru: "выходить", examples: [{ ko: "다음 역에서 내리세요.", ru: "Выходите на следующей станции." }] },
      { id: "v-yeok", ko: "역", ru: "станция", examples: [{ ko: "서울역에서 만나요.", ru: "Встретимся на Сеульском вокзале." }] },
      { id: "v-jeongryujang", ko: "정류장", ru: "остановка", examples: [{ ko: "버스 정류장이 어디예요?", ru: "Где автобусная остановка?" }] },
      { id: "v-gil", ko: "길", ru: "дорога", examples: [{ ko: "이 길로 가세요.", ru: "Идите этой дорогой." }] },
      { id: "v-meolda", ko: "멀다", ru: "далёкий", examples: [{ ko: "집이 멀어요.", ru: "Дом далеко." }] },
      { id: "v-gakkabda", ko: "가깝다", ru: "близкий", examples: [{ ko: "학교가 가까워요.", ru: "Школа близко." }] },
      { id: "v-ppareuda", ko: "빠르다", ru: "быстрый", examples: [{ ko: "지하철이 더 빨라요.", ru: "Метро быстрее." }] },
      { id: "v-georeogada", ko: "걸어가다", ru: "идти пешком", examples: [{ ko: "걸어서 가요.", ru: "Иду пешком." }] },
      { id: "v-cha", ko: "차", ru: "машина / чай", examples: [{ ko: "차를 운전해요.", ru: "Вожу машину." }] },
    ],
  },
  {
    id: "family",
    titleKo: "가족",
    titleRu: "Семья",
    topicIds: ["u16"],
    words: [
      { id: "v-gajok", ko: "가족", ru: "семья", examples: [{ ko: "가족이 네 명이에요.", ru: "В семье четыре человека." }] },
      { id: "v-abeoji", ko: "아버지", ru: "отец", examples: [{ ko: "아버지는 의사예요.", ru: "Отец — врач." }] },
      { id: "v-eomeoni", ko: "어머니", ru: "мать", examples: [{ ko: "어머니는 선생님이에요.", ru: "Мать — учительница." }] },
      { id: "v-hyeong", ko: "형", ru: "старший брат (для муж.)", examples: [{ ko: "형이 있어요.", ru: "Есть старший брат." }] },
      { id: "v-oppa", ko: "오빠", ru: "старший брат (для жен.)", examples: [{ ko: "오빠가 대학생이에요.", ru: "Оппа — студент." }] },
      { id: "v-nuna", ko: "누나", ru: "старшая сестра (для муж.)", examples: [{ ko: "누나를 만났어요.", ru: "Встретил нуну." }] },
      { id: "v-eonni", ko: "언니", ru: "старшая сестра (для жен.)", examples: [{ ko: "언니가 친절해요.", ru: "Унни добрая." }] },
      { id: "v-namdongsaeng", ko: "남동생", ru: "младший брат", examples: [{ ko: "남동생이 귀여워요.", ru: "Младший брат милый." }] },
      { id: "v-yeodongsaeng", ko: "여동생", ru: "младшая сестра", examples: [{ ko: "여동생이 있어요.", ru: "Есть младшая сестра." }] },
      { id: "v-halabeoji", ko: "할아버지", ru: "дедушка", examples: [{ ko: "할아버지께 전화해요.", ru: "Звоню дедушке." }] },
      { id: "v-halmeoni", ko: "할머니", ru: "бабушка", examples: [{ ko: "할머니가 요리를 잘하세요.", ru: "Бабушка хорошо готовит." }] },
      { id: "v-gohyang", ko: "고향", ru: "родина / родной город", examples: [{ ko: "고향이 어디예요?", ru: "Откуда вы родом?" }] },
      { id: "v-bumonim", ko: "부모님", ru: "родители", examples: [{ ko: "부모님과 살아요.", ru: "Живу с родителями." }] },
    ],
  },
  {
    id: "health",
    titleKo: "건강",
    titleRu: "Здоровье",
    topicIds: ["u15"],
    words: [
      { id: "v-apuda", ko: "아프다", ru: "болеть", examples: [{ ko: "머리가 아파요.", ru: "Голова болит." }] },
      { id: "v-meori", ko: "머리", ru: "голова", examples: [{ ko: "머리가 아파요.", ru: "Болит голова." }] },
      { id: "v-bae", ko: "배", ru: "живот", examples: [{ ko: "배가 아파요.", ru: "Живот болит." }] },
      { id: "v-mok", ko: "목", ru: "горло / шея", examples: [{ ko: "목이 아파요.", ru: "Горло болит." }] },
      { id: "v-giun", ko: "기운", ru: "сила / энергия", examples: [{ ko: "기운이 없어요.", ru: "Нет сил." }] },
      { id: "v-yak", ko: "약", ru: "лекарство", examples: [{ ko: "약을 먹어요.", ru: "Принимаю лекарство." }] },
      { id: "v-byeongwon", ko: "병원", ru: "больница", examples: [{ ko: "병원에 가야 돼요.", ru: "Нужно идти в больницу." }] },
      { id: "v-yakguk", ko: "약국", ru: "аптека", examples: [{ ko: "약국에서 약을 사요.", ru: "Покупаю лекарство в аптеке." }] },
      { id: "v-gamgi", ko: "감기", ru: "простуда", examples: [{ ko: "감기에 걸렸어요.", ru: "Простудился." }] },
      { id: "v-yeol", ko: "열", ru: "температура", examples: [{ ko: "열이 있어요.", ru: "Есть температура." }] },
      { id: "v-pisagonhada", ko: "피곤하다", ru: "усталый", examples: [{ ko: "너무 피곤해요.", ru: "Очень устал." }] },
      { id: "v-geon-gang", ko: "건강하다", ru: "здоровый", examples: [{ ko: "건강하세요!", ru: "Будьте здоровы!" }] },
      { id: "v-hyuga", ko: "휴지", ru: "салфетка / туалетная бумага", examples: [{ ko: "휴지가 필요해요.", ru: "Нужны салфетки." }] },
      { id: "v-jusahada", ko: "주사", ru: "укол", examples: [{ ko: "주사를 맞았어요.", ru: "Сделал укол." }] },
    ],
  },
  {
    id: "phone",
    titleKo: "전화",
    titleRu: "Телефон",
    topicIds: ["u11"],
    words: [
      { id: "v-jeonhwa", ko: "전화", ru: "телефон / звонок", examples: [{ ko: "전화하세요.", ru: "Позвоните." }] },
      { id: "v-jeonhwahada", ko: "전화하다", ru: "звонить", examples: [{ ko: "나중에 전화할게요.", ru: "Позвоню позже." }] },
      { id: "v-beonho", ko: "번호", ru: "номер", examples: [{ ko: "전화번호가 뭐예요?", ru: "Какой номер телефона?" }] },
      { id: "v-munja", ko: "문자", ru: "SMS", examples: [{ ko: "문자를 보냈어요.", ru: "Отправил сообщение." }] },
      { id: "v-batda", ko: "받다", ru: "получать / брать трубку", examples: [{ ko: "전화를 받으세요.", ru: "Возьмите трубку." }] },
      { id: "v-kkeoda", ko: "끊다", ru: "класть трубку", examples: [{ ko: "전화를 끊었어요.", ru: "Положил трубку." }] },
      { id: "v-bagkuda", ko: "바꾸다", ru: "менять / переключать", examples: [{ ko: "민수 씨로 바꿔 주세요.", ru: "Переключите на Минсу." }] },
      { id: "v-jamkkan", ko: "잠깐", ru: "минутку", examples: [{ ko: "잠깐만요.", ru: "Минутку." }] },
      { id: "v-jigeum-mal", ko: "지금 말하다", ru: "говорить сейчас", examples: [{ ko: "지금 말씀하실 수 있어요?", ru: "Можете сейчас говорить?" }] },
      { id: "v-yeopeopda", ko: "없다", ru: "нет / отсутствует", examples: [{ ko: "지금 자리에 없어요.", ru: "Сейчас нет на месте." }] },
      { id: "v-jeonhal", ko: "전하다", ru: "передать (сообщение)", examples: [{ ko: "전해 주세요.", ru: "Передайте, пожалуйста." }] },
      { id: "v-dahsi", ko: "다시", ru: "снова", examples: [{ ko: "다시 전화할게요.", ru: "Позвоню ещё раз." }] },
    ],
  },
  {
    id: "plans",
    titleKo: "계획",
    titleRu: "Планы",
    topicIds: ["u08"],
    words: [
      { id: "v-gyehoek", ko: "계획", ru: "план", examples: [{ ko: "계획이 있어요?", ru: "Есть планы?" }] },
      { id: "v-banghak", ko: "방학", ru: "каникулы", examples: [{ ko: "방학 동안 뭐 할 거예요?", ru: "Что будете делать на каникулах?" }] },
      { id: "v-yaksok", ko: "약속", ru: "договорённость", examples: [{ ko: "약속이 있어요.", ru: "У меня встреча." }] },
      { id: "v-junbihada", ko: "준비하다", ru: "готовить(ся)", examples: [{ ko: "여행을 준비해요.", ru: "Готовлюсь к поездке." }] },
      { id: "v-sibjak", ko: "시작하다", ru: "начинать", examples: [{ ko: "내일부터 시작해요.", ru: "Начинаю с завтра." }] },
      { id: "v-kkeutnada", ko: "끝나다", ru: "заканчиваться", examples: [{ ko: "수업이 끝났어요.", ru: "Урок закончился." }] },
      { id: "v-yejeong", ko: "예정", ru: "расписание / намерение", examples: [{ ko: "방문할 예정이에요.", ru: "Планирую навестить." }] },
      { id: "v-hu", ko: "후", ru: "после", examples: [{ ko: "수업 후에 만나요.", ru: "Встретимся после урока." }] },
      { id: "v-jeon", ko: "전", ru: "до / перед", examples: [{ ko: "가기 전에 전화해요.", ru: "Перед уходом звоню." }] },
      { id: "v-dongan", ko: "동안", ru: "в течение", examples: [{ ko: "한 시간 동안 기다렸어요.", ru: "Ждал час." }] },
    ],
  },
];

export function getDomain(id: string): VocabDomain | undefined {
  return vocabDomains.find((d) => d.id === id);
}

export function getWord(id: string): { domain: VocabDomain; word: VocabDomain["words"][number] } | undefined {
  for (const domain of vocabDomains) {
    const word = domain.words.find((w) => w.id === id);
    if (word) return { domain, word };
  }
  return undefined;
}
