import type { RelationFact } from "@/lib/scene/relations";
import type { Scene, SceneEntity } from "@/lib/scene/types";

export type LocationTask =
  | { type: "describe"; sceneId: string; subjectId: string; promptRu: string }
  | {
      type: "command";
      sceneId: string;
      subjectId: string;
      goal: RelationFact;
      promptRu: string;
    }
  | {
      type: "fix";
      sceneId: string;
      subjectId: string;
      goal: RelationFact;
      wrongSentence: string;
      promptRu: string;
    };

export type VocabWord = { ko: string; ru: string };

function entity(
  partial: Omit<SceneEntity, "ko" | "ru"> & { ko: string; ru: string },
): SceneEntity {
  return partial;
}

export const scenes: Scene[] = [
  {
    id: "street",
    kind: "street",
    cols: 9,
    rows: 3,
    entities: [
      entity({
        id: "eunhaeng",
        kind: "building",
        sprite: "bank",
        ko: "은행",
        ru: "банк",
        col: 0,
        row: 1,
        w: 1,
        h: 1,
      }),
      entity({
        id: "yakguk",
        kind: "building",
        sprite: "pharmacy",
        ko: "약국",
        ru: "аптека",
        col: 2,
        row: 1,
        w: 1,
        h: 1,
      }),
      entity({
        id: "seojeom",
        kind: "building",
        sprite: "bookstore",
        ko: "서점",
        ru: "книжный магазин",
        col: 4,
        row: 1,
        w: 1,
        h: 1,
      }),
      entity({
        id: "kape",
        kind: "building",
        sprite: "cafe",
        ko: "카페",
        ru: "кафе",
        col: 6,
        row: 1,
        w: 1,
        h: 1,
      }),
      entity({
        id: "pyeonuijeom",
        kind: "building",
        sprite: "convenience",
        ko: "편의점",
        ru: "минимаркет",
        col: 8,
        row: 1,
        w: 1,
        h: 1,
      }),
      entity({
        id: "namu",
        kind: "decor",
        sprite: "tree",
        ko: "나무",
        ru: "дерево",
        col: 1,
        row: 0,
      }),
      entity({
        id: "minsu",
        kind: "person",
        sprite: "person",
        ko: "민수",
        ru: "Минсу",
        col: 3,
        row: 2,
        movable: true,
      }),
    ],
  },
  {
    id: "classroom",
    kind: "classroom",
    cols: 6,
    rows: 3,
    entities: [
      entity({
        id: "chilpan",
        kind: "object",
        sprite: "blackboard",
        ko: "칠판",
        ru: "доска",
        col: 2,
        row: 0,
        w: 1,
        h: 1,
      }),
      entity({
        id: "sigye",
        kind: "object",
        sprite: "clock",
        ko: "시계",
        ru: "часы",
        col: 5,
        row: 0,
      }),
      entity({
        id: "changmun",
        kind: "object",
        sprite: "window",
        ko: "창문",
        ru: "окно",
        col: 0,
        row: 0,
      }),
      entity({
        id: "mun",
        kind: "object",
        sprite: "door",
        ko: "문",
        ru: "дверь",
        col: 5,
        row: 1,
      }),
      entity({
        id: "chaeksang",
        kind: "object",
        sprite: "desk",
        ko: "책상",
        ru: "парта",
        col: 1,
        row: 1,
      }),
      entity({
        id: "desk-2",
        kind: "object",
        sprite: "desk",
        ko: "책상",
        ru: "парта",
        col: 3,
        row: 1,
      }),
      entity({
        id: "uija",
        kind: "object",
        sprite: "chair",
        ko: "의자",
        ru: "стул",
        col: 1,
        row: 2,
      }),
      entity({
        id: "chaek",
        kind: "object",
        sprite: "book",
        ko: "책",
        ru: "книга",
        col: 3,
        row: 2,
      }),
      entity({
        id: "keompyuteo",
        kind: "object",
        sprite: "computer",
        ko: "컴퓨터",
        ru: "компьютер",
        col: 4,
        row: 1,
      }),
      entity({
        id: "gabang",
        kind: "object",
        sprite: "bag",
        ko: "가방",
        ru: "сумка",
        col: 2,
        row: 2,
        movable: true,
      }),
      entity({
        id: "yuna",
        kind: "person",
        sprite: "person-2",
        ko: "유나",
        ru: "Юна",
        col: 0,
        row: 2,
        movable: true,
      }),
      entity({
        id: "jihun",
        kind: "person",
        sprite: "person",
        ko: "지훈",
        ru: "Джихун",
        col: 5,
        row: 2,
      }),
    ],
  },
  {
    id: "building-cut",
    kind: "building-cut",
    cols: 4,
    rows: 3,
    entities: [
      entity({
        id: "samusil",
        kind: "room",
        sprite: "office",
        ko: "사무실",
        ru: "офис",
        col: 0,
        row: 0,
        w: 1,
        h: 1,
      }),
      entity({
        id: "doseogwan",
        kind: "room",
        sprite: "library",
        ko: "도서관",
        ru: "библиотека",
        col: 0,
        row: 1,
        w: 1,
        h: 1,
      }),
      entity({
        id: "hwajangsil",
        kind: "room",
        sprite: "toilet",
        ko: "화장실",
        ru: "туалет",
        col: 2,
        row: 1,
        w: 1,
        h: 1,
      }),
      entity({
        id: "sikdang",
        kind: "room",
        sprite: "restaurant",
        ko: "식당",
        ru: "столовая",
        col: 0,
        row: 2,
        w: 1,
        h: 1,
      }),
      entity({
        id: "kape",
        kind: "room",
        sprite: "cafe",
        ko: "카페",
        ru: "кафе",
        col: 2,
        row: 2,
        w: 1,
        h: 1,
      }),
      entity({
        id: "sujin",
        kind: "person",
        sprite: "person-2",
        ko: "수진",
        ru: "Суджин",
        col: 0,
        row: 1,
        movable: true,
        containerId: "doseogwan",
      }),
    ],
  },
  {
    id: "room",
    kind: "room",
    cols: 6,
    rows: 3,
    entities: [
      entity({
        id: "chimdae",
        kind: "object",
        sprite: "bed",
        ko: "침대",
        ru: "кровать",
        col: 0,
        row: 1,
      }),
      entity({
        id: "sopa",
        kind: "object",
        sprite: "sofa",
        ko: "소파",
        ru: "диван",
        col: 2,
        row: 2,
      }),
      entity({
        id: "takja",
        kind: "object",
        sprite: "table",
        ko: "탁자",
        ru: "столик",
        col: 3,
        row: 2,
      }),
      entity({
        id: "chaeksang",
        kind: "object",
        sprite: "desk",
        ko: "책상",
        ru: "парта",
        col: 4,
        row: 1,
      }),
      entity({
        id: "keompyuteo",
        kind: "object",
        sprite: "computer",
        ko: "컴퓨터",
        ru: "компьютер",
        col: 5,
        row: 1,
      }),
      entity({
        id: "changmun",
        kind: "object",
        sprite: "window",
        ko: "창문",
        ru: "окно",
        col: 1,
        row: 0,
      }),
      entity({
        id: "mun",
        kind: "object",
        sprite: "door",
        ko: "문",
        ru: "дверь",
        col: 5,
        row: 0,
      }),
      entity({
        id: "sigye",
        kind: "object",
        sprite: "clock",
        ko: "시계",
        ru: "часы",
        col: 3,
        row: 0,
      }),
      entity({
        id: "minsu",
        kind: "person",
        sprite: "person",
        ko: "민수",
        ru: "Минсу",
        col: 1,
        row: 2,
        movable: true,
      }),
      entity({
        id: "yuna",
        kind: "person",
        sprite: "person-2",
        ko: "유나",
        ru: "Юна",
        col: 4,
        row: 2,
      }),
    ],
  },
];

export const sceneById: Record<string, Scene> = Object.fromEntries(
  scenes.map((scene) => [scene.id, scene]),
);

export const tasks: LocationTask[] = [
  {
    type: "describe",
    sceneId: "street",
    subjectId: "yakguk",
    promptRu: "Напиши по-корейски, где находится аптека (약국)",
  },
  {
    type: "describe",
    sceneId: "classroom",
    subjectId: "chilpan",
    promptRu: "Напиши по-корейски, где находится доска (칠판)",
  },
  {
    type: "describe",
    sceneId: "building-cut",
    subjectId: "sujin",
    promptRu: "Напиши по-корейски, где находится Суджин (수진)",
  },
  {
    type: "describe",
    sceneId: "room",
    subjectId: "chimdae",
    promptRu: "Напиши по-корейски, где находится кровать (침대)",
  },
  {
    type: "command",
    sceneId: "street",
    subjectId: "minsu",
    goal: { relation: "front", refIds: ["eunhaeng"] },
    promptRu:
      "Сделай так, чтобы Минсу (민수) оказался перед банком (은행). Напиши это предложение",
  },
  {
    type: "command",
    sceneId: "street",
    subjectId: "minsu",
    goal: { relation: "beside", refIds: ["seojeom"] },
    promptRu:
      "Сделай так, чтобы Минсу (민수) стоял рядом с книжным (서점). Напиши это предложение",
  },
  {
    type: "command",
    sceneId: "street",
    subjectId: "minsu",
    goal: { relation: "between", refIds: ["eunhaeng", "yakguk"] },
    promptRu:
      "Сделай так, чтобы Минсу (민수) оказался между банком (은행) и аптекой (약국). Напиши это предложение",
  },
  {
    type: "command",
    sceneId: "building-cut",
    subjectId: "sujin",
    goal: { relation: "inside", refIds: ["hwajangsil"] },
    promptRu:
      "Сделай так, чтобы Суджин (수진) оказалась в туалете (화장실). Напиши это предложение",
  },
  {
    type: "command",
    sceneId: "building-cut",
    subjectId: "sujin",
    goal: { relation: "above", refIds: ["sikdang"] },
    promptRu:
      "Сделай так, чтобы Суджин (수진) оказалась над столовой (식당). Напиши это предложение",
  },
  {
    type: "fix",
    sceneId: "classroom",
    subjectId: "gabang",
    goal: { relation: "above", refIds: ["chaeksang"] },
    wrongSentence: "가방이 책상 아래에 있어요",
    promptRu:
      "Сумка должна быть над партой (책상). Исправь предложение",
  },
  {
    type: "fix",
    sceneId: "street",
    subjectId: "minsu",
    goal: { relation: "beside", refIds: ["eunhaeng"] },
    wrongSentence: "민수가 카페 옆에 있어요",
    promptRu:
      "Минсу (민수) должен стоять рядом с банком (은행), а не с кафе. Исправь предложение",
  },
  {
    type: "fix",
    sceneId: "street",
    subjectId: "eunhaeng",
    goal: { relation: "beside", refIds: ["yakguk"] },
    wrongSentence: "은행가 약국 옆에 있어요",
    promptRu:
      "Исправь частицу у слова «банк» (은행) так, чтобы банк стоял рядом с аптекой (약국)",
  },
];

export const vocab: VocabWord[] = [
  { ko: "앞", ru: "перед" },
  { ko: "뒤", ru: "позади" },
  { ko: "옆", ru: "рядом" },
  { ko: "위", ru: "сверху" },
  { ko: "아래", ru: "снизу" },
  { ko: "밑", ru: "под" },
  { ko: "안", ru: "внутри" },
  { ko: "밖", ru: "снаружи" },
  { ko: "사이", ru: "между" },
  { ko: "근처", ru: "возле" },
  { ko: "왼쪽", ru: "слева" },
  { ko: "오른쪽", ru: "справа" },
  { ko: "층", ru: "этаж" },
  { ko: "은행", ru: "банк" },
  { ko: "약국", ru: "аптека" },
  { ko: "서점", ru: "книжный" },
  { ko: "카페", ru: "кафе" },
  { ko: "편의점", ru: "минимаркет" },
  { ko: "식당", ru: "столовая" },
  { ko: "교실", ru: "класс" },
  { ko: "책상", ru: "парта" },
  { ko: "의자", ru: "стул" },
  { ko: "가방", ru: "сумка" },
  { ko: "창문", ru: "окно" },
  { ko: "문", ru: "дверь" },
  { ko: "침대", ru: "кровать" },
  { ko: "소파", ru: "диван" },
];
